// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const checkAPIKeyExists = `-- name: CheckAPIKeyExists :one
SELECT EXISTS(SELECT 1 FROM api_keys WHERE id = $1)
`

// Checks if an API key exists by ID.
// Used by UpdateLastUsed to distinguish "not found" from "timestamp not later".
func (q *Queries) CheckAPIKeyExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkAPIKeyExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, key_type, service, version, short_token, long_secret_hash, name, is_active, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAPIKeyParams struct {
	ID             string              `json:"id"`
	KeyType        string              `json:"key_type"`
	Service        string              `json:"service"`
	Version        string              `json:"version"`
	ShortToken     string              `json:"short_token"`
	LongSecretHash string              `json:"long_secret_hash"`
	Name           string              `json:"name"`
	IsActive       bool                `json:"is_active"`
	CreatedAt      time.Time           `json:"created_at"`
	ExpiresAt      sql.Null[time.Time] `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.KeyType,
		arg.Service,
		arg.Version,
		arg.ShortToken,
		arg.LongSecretHash,
		arg.Name,
		arg.IsActive,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deactivateAPIKey = `-- name: DeactivateAPIKey :execrows
UPDATE api_keys
SET is_active = false
WHERE id = $1
`

// DATA ACCESS PATTERN: Single-query existence check via rowsAffected
// :execrows returns (int64, error) - Repository checks rowsAffected == 0 → domain.ErrNotFound
// Revokes API key with existence check in single operation
func (q *Queries) DeactivateAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByShortToken = `-- name: GetAPIKeyByShortToken :one
SELECT id, key_type, service, version, short_token, long_secret_hash, name, is_active, created_at, last_used_at, expires_at FROM api_keys
WHERE short_token = $1 AND is_active = true
`

func (q *Queries) GetAPIKeyByShortToken(ctx context.Context, shortToken string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByShortToken, shortToken)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.KeyType,
		&i.Service,
		&i.Version,
		&i.ShortToken,
		&i.LongSecretHash,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveAPIKeys = `-- name: ListActiveAPIKeys :many
SELECT id, key_type, service, version, short_token, long_secret_hash, name, is_active, created_at, last_used_at, expires_at FROM api_keys
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.KeyType,
			&i.Service,
			&i.Version,
			&i.ShortToken,
			&i.LongSecretHash,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :execrows
UPDATE api_keys
SET last_used_at = $2
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < $2)
`

type UpdateAPIKeyLastUsedParams struct {
	ID         string              `json:"id"`
	LastUsedAt sql.Null[time.Time] `json:"last_used_at"`
}

// Updates last_used_at only if the new timestamp is later than the current value.
// Returns 0 rows affected if: (1) key doesn't exist, OR (2) timestamp not later.
// Repository uses CheckAPIKeyExists to distinguish these cases.
func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
