// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_exceptions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createException = `-- name: CreateException :one
INSERT INTO recurring_template_exceptions (
    id,
    template_id,
    occurs_at,
    exception_type,
    item_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, template_id, occurs_at, exception_type, item_id, created_at
`

type CreateExceptionParams struct {
	ID            pgtype.UUID        `json:"id"`
	TemplateID    pgtype.UUID        `json:"template_id"`
	OccursAt      pgtype.Timestamptz `json:"occurs_at"`
	ExceptionType string             `json:"exception_type"`
	ItemID        pgtype.UUID        `json:"item_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateException(ctx context.Context, arg CreateExceptionParams) (RecurringTemplateException, error) {
	row := q.db.QueryRow(ctx, createException,
		arg.ID,
		arg.TemplateID,
		arg.OccursAt,
		arg.ExceptionType,
		arg.ItemID,
		arg.CreatedAt,
	)
	var i RecurringTemplateException
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OccursAt,
		&i.ExceptionType,
		&i.ItemID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteException = `-- name: DeleteException :exec
DELETE FROM recurring_template_exceptions
WHERE template_id = $1 AND occurs_at = $2
`

type DeleteExceptionParams struct {
	TemplateID pgtype.UUID        `json:"template_id"`
	OccursAt   pgtype.Timestamptz `json:"occurs_at"`
}

func (q *Queries) DeleteException(ctx context.Context, arg DeleteExceptionParams) error {
	_, err := q.db.Exec(ctx, deleteException, arg.TemplateID, arg.OccursAt)
	return err
}

const findExceptionByOccurrence = `-- name: FindExceptionByOccurrence :one
SELECT id, template_id, occurs_at, exception_type, item_id, created_at FROM recurring_template_exceptions
WHERE template_id = $1 AND occurs_at = $2
`

type FindExceptionByOccurrenceParams struct {
	TemplateID pgtype.UUID        `json:"template_id"`
	OccursAt   pgtype.Timestamptz `json:"occurs_at"`
}

func (q *Queries) FindExceptionByOccurrence(ctx context.Context, arg FindExceptionByOccurrenceParams) (RecurringTemplateException, error) {
	row := q.db.QueryRow(ctx, findExceptionByOccurrence, arg.TemplateID, arg.OccursAt)
	var i RecurringTemplateException
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OccursAt,
		&i.ExceptionType,
		&i.ItemID,
		&i.CreatedAt,
	)
	return i, err
}

const listAllExceptionsByTemplate = `-- name: ListAllExceptionsByTemplate :many
SELECT id, template_id, occurs_at, exception_type, item_id, created_at FROM recurring_template_exceptions
WHERE template_id = $1
ORDER BY occurs_at
`

func (q *Queries) ListAllExceptionsByTemplate(ctx context.Context, templateID pgtype.UUID) ([]RecurringTemplateException, error) {
	rows, err := q.db.Query(ctx, listAllExceptionsByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringTemplateException{}
	for rows.Next() {
		var i RecurringTemplateException
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.OccursAt,
			&i.ExceptionType,
			&i.ItemID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExceptions = `-- name: ListExceptions :many
SELECT id, template_id, occurs_at, exception_type, item_id, created_at FROM recurring_template_exceptions
WHERE template_id = $1
  AND occurs_at BETWEEN $2 AND $3
ORDER BY occurs_at
`

type ListExceptionsParams struct {
	TemplateID pgtype.UUID        `json:"template_id"`
	OccursAt   pgtype.Timestamptz `json:"occurs_at"`
	OccursAt_2 pgtype.Timestamptz `json:"occurs_at_2"`
}

func (q *Queries) ListExceptions(ctx context.Context, arg ListExceptionsParams) ([]RecurringTemplateException, error) {
	rows, err := q.db.Query(ctx, listExceptions, arg.TemplateID, arg.OccursAt, arg.OccursAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringTemplateException{}
	for rows.Next() {
		var i RecurringTemplateException
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.OccursAt,
			&i.ExceptionType,
			&i.ItemID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
