// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_lists.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTodoList = `-- name: CreateTodoList :exec
INSERT INTO todo_lists (id, title, create_time)
VALUES ($1, $2, $3)
`

type CreateTodoListParams struct {
	ID         uuid.UUID `json:"id"`
	Title      string    `json:"title"`
	CreateTime time.Time `json:"create_time"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) error {
	_, err := q.db.ExecContext(ctx, createTodoList, arg.ID, arg.Title, arg.CreateTime)
	return err
}

const deleteTodoList = `-- name: DeleteTodoList :execrows
DELETE FROM todo_lists
WHERE id = $1
`

// DATA ACCESS PATTERN: Single-query existence check via rowsAffected
// :execrows returns (int64, error) - Repository checks rowsAffected == 0 → domain.ErrNotFound
// Efficient detection of non-existent records without separate SELECT query
func (q *Queries) DeleteTodoList(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTodoList, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTodoList = `-- name: GetTodoList :one
SELECT id, title, create_time FROM todo_lists
WHERE id = $1
`

func (q *Queries) GetTodoList(ctx context.Context, id uuid.UUID) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(&i.ID, &i.Title, &i.CreateTime)
	return i, err
}

const listTodoLists = `-- name: ListTodoLists :many
SELECT id, title, create_time FROM todo_lists
ORDER BY create_time DESC
`

// Legacy query: Returns all lists without items (use ListTodoListsWithCounts for list views).
func (q *Queries) ListTodoLists(ctx context.Context) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, listTodoLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(&i.ID, &i.Title, &i.CreateTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListsWithCounts = `-- name: ListTodoListsWithCounts :many
SELECT 
    tl.id,
    tl.title,
    tl.create_time,
    COALESCE(COUNT(ti.id), 0)::int AS total_items,
    COALESCE(COUNT(ti.id) FILTER (WHERE ti.status IN ('TODO', 'IN_PROGRESS', 'BLOCKED')), 0)::int AS undone_items
FROM todo_lists tl
LEFT JOIN todo_items ti ON tl.id = ti.list_id
GROUP BY tl.id, tl.title, tl.create_time
ORDER BY tl.create_time DESC
`

type ListTodoListsWithCountsRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	CreateTime  time.Time `json:"create_time"`
	TotalItems  int32     `json:"total_items"`
	UndoneItems int32     `json:"undone_items"`
}

// Optimized for LIST VIEW access pattern: Returns list metadata with item counts.
// Performance: O(lists + items) with single aggregation query vs O(lists * items) loading all items.
// Use case: Dashboard/overview pages showing list summaries without loading full item details.
//
// Returns:
//   - total_items: Total count of all items in the list
//   - undone_items: Count of active items (TODO, IN_PROGRESS, BLOCKED)
//
// This query uses LEFT JOIN to ensure lists with zero items still appear with count=0.
// The FILTER clause efficiently counts only active items in a single pass.
func (q *Queries) ListTodoListsWithCounts(ctx context.Context) ([]ListTodoListsWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodoListsWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoListsWithCountsRow{}
	for rows.Next() {
		var i ListTodoListsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreateTime,
			&i.TotalItems,
			&i.UndoneItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoList = `-- name: UpdateTodoList :execrows
UPDATE todo_lists
SET title = $1
WHERE id = $2
`

type UpdateTodoListParams struct {
	Title string    `json:"title"`
	ID    uuid.UUID `json:"id"`
}

// DATA ACCESS PATTERN: Single-query existence check via rowsAffected
// :execrows returns (int64, error) - Repository checks rowsAffected == 0 → domain.ErrNotFound
// Avoids two-query anti-pattern (SELECT then UPDATE) with race condition and doubled latency
// NOTE: create_time is immutable after creation - only title can be updated
func (q *Queries) UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTodoList, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
