// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo_lists.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTodoListsWithFilters = `-- name: CountTodoListsWithFilters :one
SELECT COUNT(DISTINCT tl.id)::int AS total_count
FROM todo_lists tl
WHERE
    ($1::text IS NULL OR LOWER(tl.title) LIKE LOWER('%' || $1 || '%'))
    AND ($2::timestamptz IS NULL OR tl.create_time > $2)
    AND ($3::timestamptz IS NULL OR tl.create_time < $3)
`

type CountTodoListsWithFiltersParams struct {
	TitleContains    string             `json:"title_contains"`
	CreateTimeAfter  pgtype.Timestamptz `json:"create_time_after"`
	CreateTimeBefore pgtype.Timestamptz `json:"create_time_before"`
}

// Count total matching lists for pagination (same filters as FindTodoListsWithFilters).
func (q *Queries) CountTodoListsWithFilters(ctx context.Context, arg CountTodoListsWithFiltersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTodoListsWithFilters, arg.TitleContains, arg.CreateTimeAfter, arg.CreateTimeBefore)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const createTodoList = `-- name: CreateTodoList :exec
INSERT INTO todo_lists (id, title, create_time)
VALUES ($1, $2, $3)
`

type CreateTodoListParams struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	CreateTime pgtype.Timestamptz `json:"create_time"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) error {
	_, err := q.db.Exec(ctx, createTodoList, arg.ID, arg.Title, arg.CreateTime)
	return err
}

const deleteTodoList = `-- name: DeleteTodoList :execrows
DELETE FROM todo_lists
WHERE id = $1
`

// DATA ACCESS PATTERN: Single-query existence check via rowsAffected
// :execrows returns (int64, error) - Repository checks rowsAffected == 0 → domain.ErrNotFound
// Efficient detection of non-existent records without separate SELECT query
func (q *Queries) DeleteTodoList(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTodoList, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findTodoListsWithFilters = `-- name: FindTodoListsWithFilters :many
SELECT
    tl.id,
    tl.title,
    tl.create_time,
    COALESCE(COUNT(ti.id), 0)::int AS total_items,
    COALESCE(COUNT(ti.id) FILTER (WHERE ti.status = ANY($1::text[])), 0)::int AS undone_items
FROM todo_lists tl
LEFT JOIN todo_items ti ON tl.id = ti.list_id
WHERE
    ($2::text IS NULL OR LOWER(tl.title) LIKE LOWER('%' || $2 || '%'))
    AND ($3::timestamptz IS NULL OR tl.create_time > $3)
    AND ($4::timestamptz IS NULL OR tl.create_time < $4)
GROUP BY tl.id, tl.title, tl.create_time
ORDER BY
    CASE
        WHEN $5 = 'title' AND $6 = 'asc' THEN tl.title
    END ASC,
    CASE
        WHEN $5 = 'title' AND $6 = 'desc' THEN tl.title
    END DESC,
    CASE
        WHEN $5 = 'create_time' AND $6 = 'asc' THEN tl.create_time
        WHEN ($5 IS NULL OR $5 = '') AND ($6 IS NULL OR $6 = '' OR $6 = 'asc') THEN tl.create_time
    END ASC,
    CASE
        WHEN $5 = 'create_time' AND $6 = 'desc' THEN tl.create_time
        WHEN ($5 IS NULL OR $5 = '') AND $6 = 'desc' THEN tl.create_time
    END DESC
LIMIT $8
OFFSET $7
`

type FindTodoListsWithFiltersParams struct {
	UndoneStatuses   []string           `json:"undone_statuses"`
	TitleContains    string             `json:"title_contains"`
	CreateTimeAfter  pgtype.Timestamptz `json:"create_time_after"`
	CreateTimeBefore pgtype.Timestamptz `json:"create_time_before"`
	OrderBy          interface{}        `json:"order_by"`
	OrderDir         interface{}        `json:"order_dir"`
	PageOffset       int32              `json:"page_offset"`
	PageLimit        int32              `json:"page_limit"`
}

type FindTodoListsWithFiltersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	CreateTime  pgtype.Timestamptz `json:"create_time"`
	TotalItems  int32              `json:"total_items"`
	UndoneItems int32              `json:"undone_items"`
}

// Advanced list query with filtering, sorting, and pagination.
// Supports AIP-160-style filtering and AIP-132-style sorting.
//
// Parameters use nullable types for optional filters:
//   - title_contains: Filters by title substring (case-insensitive)
//   - create_time_after: Filters lists created after this time
//   - create_time_before: Filters lists created before this time
//   - order_by: Column to sort by ("create_time" or "title")
//   - order_dir: Sort direction ("asc" or "desc")
//   - page_limit: Maximum number of results to return
//   - page_offset: Number of results to skip
func (q *Queries) FindTodoListsWithFilters(ctx context.Context, arg FindTodoListsWithFiltersParams) ([]FindTodoListsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, findTodoListsWithFilters,
		arg.UndoneStatuses,
		arg.TitleContains,
		arg.CreateTimeAfter,
		arg.CreateTimeBefore,
		arg.OrderBy,
		arg.OrderDir,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTodoListsWithFiltersRow{}
	for rows.Next() {
		var i FindTodoListsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreateTime,
			&i.TotalItems,
			&i.UndoneItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoList = `-- name: GetTodoList :one
SELECT id, title, create_time FROM todo_lists
WHERE id = $1
`

func (q *Queries) GetTodoList(ctx context.Context, id pgtype.UUID) (TodoList, error) {
	row := q.db.QueryRow(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(&i.ID, &i.Title, &i.CreateTime)
	return i, err
}

const getTodoListWithCounts = `-- name: GetTodoListWithCounts :one
SELECT
    tl.id,
    tl.title,
    tl.create_time,
    COALESCE(COUNT(ti.id), 0)::int AS total_items,
    COALESCE(COUNT(ti.id) FILTER (WHERE ti.status = ANY($1::text[])), 0)::int AS undone_items
FROM todo_lists tl
LEFT JOIN todo_items ti ON tl.id = ti.list_id
WHERE tl.id = $2
GROUP BY tl.id, tl.title, tl.create_time
`

type GetTodoListWithCountsParams struct {
	UndoneStatuses []string    `json:"undone_statuses"`
	ID             pgtype.UUID `json:"id"`
}

type GetTodoListWithCountsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	CreateTime  pgtype.Timestamptz `json:"create_time"`
	TotalItems  int32              `json:"total_items"`
	UndoneItems int32              `json:"undone_items"`
}

// Returns a single list by ID with item counts (for detail view).
// undone_statuses parameter: domain layer defines which statuses count as "undone".
func (q *Queries) GetTodoListWithCounts(ctx context.Context, arg GetTodoListWithCountsParams) (GetTodoListWithCountsRow, error) {
	row := q.db.QueryRow(ctx, getTodoListWithCounts, arg.UndoneStatuses, arg.ID)
	var i GetTodoListWithCountsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreateTime,
		&i.TotalItems,
		&i.UndoneItems,
	)
	return i, err
}

const listTodoLists = `-- name: ListTodoLists :many
SELECT id, title, create_time FROM todo_lists
ORDER BY create_time DESC
`

// Legacy query: Returns all lists without items (use ListTodoListsWithCounts for list views).
func (q *Queries) ListTodoLists(ctx context.Context) ([]TodoList, error) {
	rows, err := q.db.Query(ctx, listTodoLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(&i.ID, &i.Title, &i.CreateTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListsWithCounts = `-- name: ListTodoListsWithCounts :many
SELECT
    tl.id,
    tl.title,
    tl.create_time,
    COALESCE(COUNT(ti.id), 0)::int AS total_items,
    COALESCE(COUNT(ti.id) FILTER (WHERE ti.status = ANY($1::text[])), 0)::int AS undone_items
FROM todo_lists tl
LEFT JOIN todo_items ti ON tl.id = ti.list_id
GROUP BY tl.id, tl.title, tl.create_time
ORDER BY tl.create_time DESC
`

type ListTodoListsWithCountsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	CreateTime  pgtype.Timestamptz `json:"create_time"`
	TotalItems  int32              `json:"total_items"`
	UndoneItems int32              `json:"undone_items"`
}

// Optimized for LIST VIEW access pattern: Returns list metadata with item counts.
// Performance: O(lists + items) with single aggregation query vs O(lists * items) loading all items.
// Use case: Dashboard/overview pages showing list summaries without loading full item details.
//
// Returns:
//   - total_items: Total count of all items in the list
//   - undone_items: Count of items matching provided statuses (domain defines "undone")
//
// This query uses LEFT JOIN to ensure lists with zero items still appear with count=0.
// The FILTER clause efficiently counts only matching items in a single pass.
func (q *Queries) ListTodoListsWithCounts(ctx context.Context, undoneStatuses []string) ([]ListTodoListsWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listTodoListsWithCounts, undoneStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodoListsWithCountsRow{}
	for rows.Next() {
		var i ListTodoListsWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreateTime,
			&i.TotalItems,
			&i.UndoneItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoList = `-- name: UpdateTodoList :execrows
UPDATE todo_lists
SET title = $1
WHERE id = $2
`

type UpdateTodoListParams struct {
	Title string      `json:"title"`
	ID    pgtype.UUID `json:"id"`
}

// DATA ACCESS PATTERN: Single-query existence check via rowsAffected
// :execrows returns (int64, error) - Repository checks rowsAffected == 0 → domain.ErrNotFound
// Avoids two-query anti-pattern (SELECT then UPDATE) with race condition and doubled latency
// NOTE: create_time is immutable after creation - only title can be updated
func (q *Queries) UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTodoList, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
