version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - containedctx
    - copyloopvar
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - goconst

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
