version: "2"

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  exclusions:
    paths:
      - ".*testdata.*"
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - copyloopvar
    - dupl
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - goconst

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
