// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ItemPriority.
const (
	ItemPriorityHigh   ItemPriority = "high"
	ItemPriorityLow    ItemPriority = "low"
	ItemPriorityMedium ItemPriority = "medium"
	ItemPriorityUrgent ItemPriority = "urgent"
)

// Defines values for ItemStatus.
const (
	ItemStatusArchived   ItemStatus = "archived"
	ItemStatusBlocked    ItemStatus = "blocked"
	ItemStatusCancelled  ItemStatus = "cancelled"
	ItemStatusDone       ItemStatus = "done"
	ItemStatusInProgress ItemStatus = "in_progress"
	ItemStatusTodo       ItemStatus = "todo"
)

// Defines values for RecurrencePattern.
const (
	Biweekly  RecurrencePattern = "biweekly"
	Daily     RecurrencePattern = "daily"
	Monthly   RecurrencePattern = "monthly"
	Quarterly RecurrencePattern = "quarterly"
	Weekdays  RecurrencePattern = "weekdays"
	Weekly    RecurrencePattern = "weekly"
	Yearly    RecurrencePattern = "yearly"
)

// Defines values for ListListsParamsSortBy.
const (
	CreateTime ListListsParamsSortBy = "create_time"
	Title      ListListsParamsSortBy = "title"
)

// Defines values for ListListsParamsSortDir.
const (
	ListListsParamsSortDirAsc  ListListsParamsSortDir = "asc"
	ListListsParamsSortDirDesc ListListsParamsSortDir = "desc"
)

// Defines values for ListItemsParamsStatus.
const (
	ListItemsParamsStatusArchived   ListItemsParamsStatus = "archived"
	ListItemsParamsStatusBlocked    ListItemsParamsStatus = "blocked"
	ListItemsParamsStatusCancelled  ListItemsParamsStatus = "cancelled"
	ListItemsParamsStatusDone       ListItemsParamsStatus = "done"
	ListItemsParamsStatusInProgress ListItemsParamsStatus = "in_progress"
	ListItemsParamsStatusTodo       ListItemsParamsStatus = "todo"
)

// Defines values for ListItemsParamsPriority.
const (
	ListItemsParamsPriorityHigh   ListItemsParamsPriority = "high"
	ListItemsParamsPriorityLow    ListItemsParamsPriority = "low"
	ListItemsParamsPriorityMedium ListItemsParamsPriority = "medium"
	ListItemsParamsPriorityUrgent ListItemsParamsPriority = "urgent"
)

// Defines values for ListItemsParamsSortBy.
const (
	CreatedAt ListItemsParamsSortBy = "created_at"
	DueTime   ListItemsParamsSortBy = "due_time"
	Priority  ListItemsParamsSortBy = "priority"
	UpdatedAt ListItemsParamsSortBy = "updated_at"
)

// Defines values for ListItemsParamsSortDir.
const (
	ListItemsParamsSortDirAsc  ListItemsParamsSortDir = "asc"
	ListItemsParamsSortDirDesc ListItemsParamsSortDir = "desc"
)

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	DueTime *time.Time `json:"due_time,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration   *string             `json:"estimated_duration,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *ItemPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`
	Tags                *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone (e.g., 'Europe/Stockholm')
	Timezone *string `json:"timezone,omitempty"`
	Title    string  `json:"title"`
}

// CreateItemResponse defines model for CreateItemResponse.
type CreateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// CreateListRequest defines model for CreateListRequest.
type CreateListRequest struct {
	Title string `json:"title"`
}

// CreateListResponse defines model for CreateListResponse.
type CreateListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// CreateRecurringTemplateRequest defines model for CreateRecurringTemplateRequest.
type CreateRecurringTemplateRequest struct {
	// DueOffset ISO 8601 duration offset from instance date
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration    *string       `json:"estimated_duration,omitempty"`
	GenerationWindowDays *int          `json:"generation_window_days,omitempty"`
	Priority             *ItemPriority `json:"priority,omitempty"`

	// RecurrenceConfig JSON config for pattern-specific settings
	RecurrenceConfig  *string           `json:"recurrence_config,omitempty"`
	RecurrencePattern RecurrencePattern `json:"recurrence_pattern"`
	Tags              *[]string         `json:"tags,omitempty"`
	Title             string            `json:"title"`
}

// CreateRecurringTemplateResponse defines model for CreateRecurringTemplateResponse.
type CreateRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Details *[]struct {
			Field *string `json:"field,omitempty"`
			Issue *string `json:"issue,omitempty"`
		} `json:"details,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// GetListResponse defines model for GetListResponse.
type GetListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// GetRecurringTemplateResponse defines model for GetRecurringTemplateResponse.
type GetRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// ItemPriority defines model for ItemPriority.
type ItemPriority string

// ItemStatus defines model for ItemStatus.
type ItemStatus string

// ListItemsResponse defines model for ListItemsResponse.
type ListItemsResponse struct {
	Items         *[]TodoItem `json:"items,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// ListListsResponse defines model for ListListsResponse.
type ListListsResponse struct {
	Lists         *[]TodoList `json:"lists,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// ListRecurringTemplatesResponse defines model for ListRecurringTemplatesResponse.
type ListRecurringTemplatesResponse struct {
	Templates *[]RecurringItemTemplate `json:"templates,omitempty"`
}

// RecurrencePattern defines model for RecurrencePattern.
type RecurrencePattern string

// RecurringItemTemplate defines model for RecurringItemTemplate.
type RecurringItemTemplate struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DueOffset ISO 8601 duration
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration    *string             `json:"estimated_duration,omitempty"`
	GenerationWindowDays *int                `json:"generation_window_days,omitempty"`
	Id                   *openapi_types.UUID `json:"id,omitempty"`
	IsActive             *bool               `json:"is_active,omitempty"`
	LastGeneratedUntil   *time.Time          `json:"last_generated_until,omitempty"`
	ListId               *openapi_types.UUID `json:"list_id,omitempty"`
	Priority             *ItemPriority       `json:"priority,omitempty"`

	// RecurrenceConfig JSON configuration
	RecurrenceConfig  *string            `json:"recurrence_config,omitempty"`
	RecurrencePattern *RecurrencePattern `json:"recurrence_pattern,omitempty"`
	Tags              *[]string          `json:"tags,omitempty"`
	Title             *string            `json:"title,omitempty"`
	UpdatedAt         *time.Time         `json:"updated_at,omitempty"`
}

// TodoItem defines model for TodoItem.
type TodoItem struct {
	// ActualDuration ISO 8601 duration
	ActualDuration *string    `json:"actual_duration,omitempty"`
	CreateTime     *time.Time `json:"create_time,omitempty"`
	DueTime        *time.Time `json:"due_time,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration *string `json:"estimated_duration,omitempty"`

	// Etag Entity tag for optimistic concurrency control (RFC 7232). Quoted string format like "1", "2", etc.
	Etag                *string             `json:"etag,omitempty"`
	Id                  *openapi_types.UUID `json:"id,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *ItemPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`
	Status              *ItemStatus         `json:"status,omitempty"`
	Tags                *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone
	Timezone  *string    `json:"timezone,omitempty"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	CreateTime *time.Time          `json:"create_time,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Title      *string             `json:"title,omitempty"`

	// TotalItems Total items in this list
	TotalItems *int `json:"total_items,omitempty"`

	// UndoneItems Items not yet done
	UndoneItems *int `json:"undone_items,omitempty"`
}

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Item *TodoItem `json:"item,omitempty"`

	// UpdateMask Fields to update (field mask)
	UpdateMask *[]string `json:"update_mask,omitempty"`
}

// UpdateItemResponse defines model for UpdateItemResponse.
type UpdateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// UpdateRecurringTemplateRequest defines model for UpdateRecurringTemplateRequest.
type UpdateRecurringTemplateRequest struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`

	// UpdateMask Fields to update (field mask)
	UpdateMask *[]string `json:"update_mask,omitempty"`
}

// UpdateRecurringTemplateResponse defines model for UpdateRecurringTemplateResponse.
type UpdateRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListListsParams defines parameters for ListLists.
type ListListsParams struct {
	// PageSize Number of lists per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Page token from previous response
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// TitleContains Filter by title substring (case-insensitive)
	TitleContains *string `form:"title_contains,omitempty" json:"title_contains,omitempty"`

	// CreatedAfter Filter lists created after this time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter lists created before this time
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`

	// SortBy Field to sort by
	SortBy *ListListsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir *ListListsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// ListListsParamsSortBy defines parameters for ListLists.
type ListListsParamsSortBy string

// ListListsParamsSortDir defines parameters for ListLists.
type ListListsParamsSortDir string

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Status Filter by item status (can specify multiple).
	// If not specified, archived and cancelled items are excluded by default.
	// Use status=archived to explicitly include archived items.
	Status *[]ListItemsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Priority Filter by item priority (can specify multiple for OR logic)
	Priority *[]ListItemsParamsPriority `form:"priority,omitempty" json:"priority,omitempty"`

	// Tags Filter by tags (items must have all specified tags)
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// SortBy Field to sort by
	SortBy *ListItemsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir   *ListItemsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	PageSize  *int                    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string                 `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListItemsParamsStatus defines parameters for ListItems.
type ListItemsParamsStatus string

// ListItemsParamsPriority defines parameters for ListItems.
type ListItemsParamsPriority string

// ListItemsParamsSortBy defines parameters for ListItems.
type ListItemsParamsSortBy string

// ListItemsParamsSortDir defines parameters for ListItems.
type ListItemsParamsSortDir string

// ListRecurringTemplatesParams defines parameters for ListRecurringTemplates.
type ListRecurringTemplatesParams struct {
	// ActiveOnly Filter for active templates only
	ActiveOnly *bool `form:"active_only,omitempty" json:"active_only,omitempty"`
}

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// CreateRecurringTemplateJSONRequestBody defines body for CreateRecurringTemplate for application/json ContentType.
type CreateRecurringTemplateJSONRequestBody = CreateRecurringTemplateRequest

// UpdateRecurringTemplateJSONRequestBody defines body for UpdateRecurringTemplate for application/json ContentType.
type UpdateRecurringTemplateJSONRequestBody = UpdateRecurringTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all todo lists with pagination
	// (GET /v1/lists)
	ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams)
	// Create a new todo list
	// (POST /v1/lists)
	CreateList(w http.ResponseWriter, r *http.Request)
	// Get a todo list by ID
	// (GET /v1/lists/{id})
	GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List items in a list with filtering and sorting
	// (GET /v1/lists/{list_id}/items)
	ListItems(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListItemsParams)
	// Create a new item in a list
	// (POST /v1/lists/{list_id}/items)
	CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Update an existing item
	// (PATCH /v1/lists/{list_id}/items/{item_id})
	UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID)
	// List recurring templates for a list
	// (GET /v1/lists/{list_id}/recurring-templates)
	ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams)
	// Create a recurring item template
	// (POST /v1/lists/{list_id}/recurring-templates)
	CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Delete a recurring template
	// (DELETE /v1/lists/{list_id}/recurring-templates/{template_id})
	DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
	// Get a recurring template by ID
	// (GET /v1/lists/{list_id}/recurring-templates/{template_id})
	GetRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
	// Update a recurring template
	// (PATCH /v1/lists/{list_id}/recurring-templates/{template_id})
	UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all todo lists with pagination
// (GET /v1/lists)
func (_ Unimplemented) ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new todo list
// (POST /v1/lists)
func (_ Unimplemented) CreateList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a todo list by ID
// (GET /v1/lists/{id})
func (_ Unimplemented) GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List items in a list with filtering and sorting
// (GET /v1/lists/{list_id}/items)
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new item in a list
// (POST /v1/lists/{list_id}/items)
func (_ Unimplemented) CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing item
// (PATCH /v1/lists/{list_id}/items/{item_id})
func (_ Unimplemented) UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recurring templates for a list
// (GET /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a recurring item template
// (POST /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a recurring template
// (DELETE /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a recurring template by ID
// (GET /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) GetRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a recurring template
// (PATCH /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLists operation middleware
func (siw *ServerInterfaceWrapper) ListLists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListListsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "title_contains" -------------

	err = runtime.BindQueryParameter("form", true, false, "title_contains", r.URL.Query(), &params.TitleContains)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title_contains", Err: err})
		return
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateList operation middleware
func (siw *ServerInterfaceWrapper) CreateList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameter("form", true, false, "priority", r.URL.Query(), &params.Priority)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "priority", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", r.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecurringTemplatesParams

	// ------------- Optional query parameter "active_only" -------------

	err = runtime.BindQueryParameter("form", true, false, "active_only", r.URL.Query(), &params.ActiveOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active_only", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringTemplates(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringTemplate(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists", wrapper.ListLists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists", wrapper.CreateList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{id}", wrapper.GetList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/items", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/items", wrapper.CreateItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/lists/{list_id}/items/{item_id}", wrapper.UpdateItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.ListRecurringTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.CreateRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.DeleteRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.GetRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.UpdateRecurringTemplate)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbX2/bOBL/KgTvgG0B1XaSdq8wcA/pbtvLodv2kvTh0AQGI41tbihSJUdJ3MDf/UBS",
	"liWLspU/TprrPhSRJZIzHP7mP3tNY5VmSoJEQ4fXVIPJlDTgfrxhySF8y8Gg/RUriSDdI8sywWOGXMn+",
	"n0ZJ+87EU0iZffq7hjEd0r/1l0v3/VfTf6u10ocFETqfzyOagIk1z+xidEgP5AUTPCG6IDyP6IFE0JIJ",
	"N/chOfFkiQF9AZqAIz+P6EeF71Quk4dj5RCMynUMRCokY0d7HtEvkuU4VZp/hwfkpUqVvCC8OC+lScqN",
	"4XJC9j8fkHOYUTu3WNZS/U0DQzhASCugyrTKQCP3gEtyGCFPwT6PlU4Z0iFNGMIL9zaiOMuADqlBzeXE",
	"ygAM8pQhJKMk18yzeL16kEefyOtfBzukHBJRuGJpJuxan493/7U3+CO0OJcGmYxhZFnozlOmudIcZ5tE",
	"bUXxeTF2HlENca7tIiOENBMMYcSTGtk850mIIrKJkx9HSN1Dc4R/wbRmjpbl/buSEJDW/sd9svhMnkFv",
	"0ovIL29ze1D9I1Tx+VSJ9JfnNSHup6B5zPof4XL0X6XPg0xyFI5eyq4+gJzglA53X72KaMrl4vdOY56T",
	"y7eca4vxr8Uip+UwdfYnxM5KVOFVoLeBLyufTadyrBJlV3GkW6h84AZbQVzucymeo6nKMqsadiKNtioB",
	"z1ubBAT3LG+SgGN0jQQOF1g9LqC6VqfVeGwAO2gm8SPJWKuULNSPOPW7R+VvLDQBCf7r6JLLRF2OEjbz",
	"3MOY5QLpcG/gjo2neUqHe7/6Q/O/lkfGJcIE9N2NAFirEys55pPmlv599Okj8R/JWGmSMbSe6oXJIOZj",
	"HhMDiFxOTGirlfWLeZs4PCxnfC4m3NLi3Jv6B3dxehOstqnHwvB2kwmXE3t8i2XD+lJ3qA2KsAhq6q9j",
	"lUBQrAkg46Iu+/rUMQeRBOdyY/LQqiG2V48vBWPYpNvs0HrvAbdtmd4DPu5R13TZnq205uErFerSGn1I",
	"eJ7SiE75ZEojmuuJjdZOA0pqFzpChrmpLoMqUdRGJaNMq4kGYxX8TKj4HGxUkFh3HlGm4ym/cG9iaz2F",
	"gCRIxArSEjLr/WX9oZvnbMJHwhWOMjaBEapzkB1BaFm0/8x62NyMRQ+g+2SxgTqzGXbdeW4B4OoGQsw1",
	"TXcFTgnjYkYjeglw7h7OePmYKolT9zQDpt3Dt5xpBF1OcR4yhKswv00L52xzMmLYPbK+USzxSBFDMxTo",
	"GMRzM2Ix8ouqjT1TSgBzHlcwg6OCLCSjXCIX3SVn1aRrNvEwocsa4T5+jNIYmWfJDdEa0sfSQja0gcWY",
	"M3FXVHqdumEK/XBJd3MhZAGQvJXIcUaQ+fBWZchTbpDHFjnFOc/sM2olyLPDd7+Rf+zu7T7vkf/kCiEh",
	"ngDxmyGCnwM5oTsnNCIndNf+AYx7QRXsqKlPpS5gyhhiE70i2thmLWFtTWCLCveBh9LSW6lK13JM665Q",
	"IROjUrR1aR3bj8R9JFwSnHJDhC8YNJ1KLm2817aUi+tctXAGSJKa9MtFQgL74sS+tkh3syLK4iRHKTPn",
	"TUbf2WTFEFTEDyPPXPpC7OhaiWmZ+xWgrujTadQZrZv2vL3KkafSvW5yx/zkjnK/uzwfMxWzps+O5Tg7",
	"snOLdgYwDXo/x2lTHkXNmmTMGEgIM8SPJi4XsOq4X1S9fZ1qCiwBTYsCtwvV3Pilmk0RM18/53KsmhQP",
	"3x4dj3PhquXWzdnszqk7YTJxVoCkTLIJpCCRXHKcktIRkGUWUVob+oeSyq5GI3oB2ngqO71Bb2APRWUg",
	"WcbpkO71Br09qz4Mp04u/YudfplGTXxsbY/H7fQgocNlHuamaZYCgjZ0+HV1Ux/z9Aw0UWO3E0My0MSm",
	"VC5tpUP6LQdtEwjJnMxctmX4d1gIktVqbrvVmtvOYLC+5jaPVrn5zCZQHKArKGYaLrjKDVl0udax5ZPA",
	"Kl8Nf9NUKoGgydmMuDMhJj8rQpFnMTPwgksD0nAb4z9vIe0m2vAZGZfmVuS95Iv0irCxfed8SeHVQmTL",
	"ZMyOrlHt5nk7sXIGY6WhMy9++L0wYy0bKmKURnI2a6Frv47c1wAUa/FCVObQ9berpfl2lo4sJwnXEBeh",
	"cStDCdctHNkVK6ww98u9DHBwGtVbu7uDwb21DJtVmkDb0A0gGlBzuLAxeh7HYMw4F8IFkS89QyE6JeP9",
	"SkPaTdnZPKXWJJ1H9FUXOvWOs3MneZoyPSs2QpgQS4NtvHXO2ITLMtVxUfRXv216aqN/ZQKWddmzob7S",
	"DQbfqGR2b4fTbFjN60V11DnMG+jY2QoD6+FRGooniw2/V8KIhMslPgJwmEdLr9u/5sm84npXW/+Ya+kT",
	"AZICsoQh65EvBsj7t8ekskpR4pn3fQaBiowB42mRUDiIjp1Z5nJis986EIv6/CYH787p4PeFxbIxxNJg",
	"uWyojqyg9Q7nTVu1UavthzYIlpcrbgWgl4OXmyeV10fuA3HvAQmrxI5nM3866wFXh8pG7JUpKXNEeuTN",
	"jBR+KCKLfoMLW8uOQzGHaSBwFYs8gaSJubIDcSfULUqbd4HemlDOReI+57RhnCS+zTojaS6QZwKe907k",
	"wdgl20UHFpIbiMXSKITZO5FWrz2xf5YroCJwZYHPUcwIl27ekoBbsnfib7VkwjUO/f6DQcUie14KpwTB",
	"lhpNKbvypzz8tVk8Mjhz2Ys9IbrxHBYpf/gkXB716ZAINeHx827yKIsIayVy4w7ecs8v77Bnq8XkmcdM",
	"mhskU3YBLvgokebGdNyrMwrBfa7h/9Ut+L+3eNvV/5YxblmqjqrnVhtaqRv+kIF4dP0wmfAd8tpt5wr1",
	"pnPo5qUD/OPnCg/vzp2jW3G3K6GbcygWkfawlo7ea+umRMOVJx/b2Z5uM9Oplq4fJdOp1ZFbwP3omc7D",
	"I7uWGjlfXgI8gOJ14Wr/2v4ZFUlTxjCeNuG+rOn/eLGlQ0BrDuX39iMqWLM31EnBBlthYIOCFWHAT6Rg",
	"XjiESQJX3Fjv4NSsu3KV3YUXtTtKrQ2B5q2nHzaNs3mBv1uz7JwQJUVbaOrHjooRgXhszISBqHFLZ+uh",
	"05qbZgFNKAetjaWeTmAU6H/5o111IwFoboqMGlP+v8Ok1j70o8RM7b3iNaj+mYOopSa4UAqXmF2rAt0t",
	"f/+6ctdo7m2fAN+ir6vP7+79j6c+DV9Q4qaNavV21f3WsV8GLvssuPFyfbKG2R9/DZJd0RiFY4vQNf6/",
	"0LStrsjtTO/TbJM0Idrol7RFDuuyzL/Q+kCp592ClsH2uemgOT9vYnoLD1G9yOf0qHqF7+upRZv/z/lB",
	"LVMxEySBCxAqS+2hRzTXoriaN+z3hR0wVQaHrwevd/os43R+Ov9fAAAA//8SDn57EkEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
