// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for RecurrencePattern.
const (
	Biweekly  RecurrencePattern = "biweekly"
	Daily     RecurrencePattern = "daily"
	Monthly   RecurrencePattern = "monthly"
	Quarterly RecurrencePattern = "quarterly"
	Weekdays  RecurrencePattern = "weekdays"
	Weekly    RecurrencePattern = "weekly"
	Yearly    RecurrencePattern = "yearly"
)

// Defines values for TaskPriority.
const (
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// Defines values for TaskStatus.
const (
	TaskStatusArchived   TaskStatus = "archived"
	TaskStatusBlocked    TaskStatus = "blocked"
	TaskStatusCancelled  TaskStatus = "cancelled"
	TaskStatusDone       TaskStatus = "done"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusTodo       TaskStatus = "todo"
)

// Defines values for ListListsParamsSortBy.
const (
	CreateTime ListListsParamsSortBy = "create_time"
	Title      ListListsParamsSortBy = "title"
)

// Defines values for ListListsParamsSortDir.
const (
	ListListsParamsSortDirAsc  ListListsParamsSortDir = "asc"
	ListListsParamsSortDirDesc ListListsParamsSortDir = "desc"
)

// Defines values for ListTasksParamsStatus.
const (
	ListTasksParamsStatusArchived   ListTasksParamsStatus = "archived"
	ListTasksParamsStatusBlocked    ListTasksParamsStatus = "blocked"
	ListTasksParamsStatusCancelled  ListTasksParamsStatus = "cancelled"
	ListTasksParamsStatusDone       ListTasksParamsStatus = "done"
	ListTasksParamsStatusInProgress ListTasksParamsStatus = "in_progress"
	ListTasksParamsStatusTodo       ListTasksParamsStatus = "todo"
)

// Defines values for ListTasksParamsPriority.
const (
	ListTasksParamsPriorityHigh   ListTasksParamsPriority = "high"
	ListTasksParamsPriorityLow    ListTasksParamsPriority = "low"
	ListTasksParamsPriorityMedium ListTasksParamsPriority = "medium"
	ListTasksParamsPriorityUrgent ListTasksParamsPriority = "urgent"
)

// Defines values for ListTasksParamsSortBy.
const (
	CreatedAt ListTasksParamsSortBy = "created_at"
	DueTime   ListTasksParamsSortBy = "due_time"
	Priority  ListTasksParamsSortBy = "priority"
	UpdatedAt ListTasksParamsSortBy = "updated_at"
)

// Defines values for ListTasksParamsSortDir.
const (
	ListTasksParamsSortDirAsc  ListTasksParamsSortDir = "asc"
	ListTasksParamsSortDirDesc ListTasksParamsSortDir = "desc"
)

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	DueTime *time.Time `json:"due_time,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration   *string             `json:"estimated_duration,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *TaskPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`
	Tags                *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone (e.g., 'Europe/Stockholm')
	Timezone *string `json:"timezone,omitempty"`
	Title    string  `json:"title"`
}

// CreateItemResponse defines model for CreateItemResponse.
type CreateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// CreateListRequest defines model for CreateListRequest.
type CreateListRequest struct {
	Title string `json:"title"`
}

// CreateListResponse defines model for CreateListResponse.
type CreateListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// CreateRecurringTemplateRequest defines model for CreateRecurringTemplateRequest.
type CreateRecurringTemplateRequest struct {
	// DueOffset ISO 8601 duration offset from instance date
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration    *string       `json:"estimated_duration,omitempty"`
	GenerationWindowDays *int          `json:"generation_window_days,omitempty"`
	Priority             *TaskPriority `json:"priority,omitempty"`

	// RecurrenceConfig JSON config for pattern-specific settings
	RecurrenceConfig  *string           `json:"recurrence_config,omitempty"`
	RecurrencePattern RecurrencePattern `json:"recurrence_pattern"`
	Tags              *[]string         `json:"tags,omitempty"`
	Title             string            `json:"title"`
}

// CreateRecurringTemplateResponse defines model for CreateRecurringTemplateResponse.
type CreateRecurringTemplateResponse struct {
	Template *RecurringTaskTemplate `json:"template,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Details *[]struct {
			Field *string `json:"field,omitempty"`
			Issue *string `json:"issue,omitempty"`
		} `json:"details,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// GetListResponse defines model for GetListResponse.
type GetListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// GetRecurringTemplateResponse defines model for GetRecurringTemplateResponse.
type GetRecurringTemplateResponse struct {
	Template *RecurringTaskTemplate `json:"template,omitempty"`
}

// ListListsResponse defines model for ListListsResponse.
type ListListsResponse struct {
	Lists         *[]TodoList `json:"lists,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// ListRecurringTemplatesResponse defines model for ListRecurringTemplatesResponse.
type ListRecurringTemplatesResponse struct {
	Templates *[]RecurringTaskTemplate `json:"templates,omitempty"`
}

// ListTasksResponse defines model for ListTasksResponse.
type ListTasksResponse struct {
	Items         *[]TodoItem `json:"items,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// RecurrencePattern defines model for RecurrencePattern.
type RecurrencePattern string

// RecurringTaskTemplate defines model for RecurringTaskTemplate.
type RecurringTaskTemplate struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DueOffset ISO 8601 duration
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration    *string             `json:"estimated_duration,omitempty"`
	GenerationWindowDays *int                `json:"generation_window_days,omitempty"`
	Id                   *openapi_types.UUID `json:"id,omitempty"`
	IsActive             *bool               `json:"is_active,omitempty"`
	LastGeneratedUntil   *time.Time          `json:"last_generated_until,omitempty"`
	ListId               *openapi_types.UUID `json:"list_id,omitempty"`
	Priority             *TaskPriority       `json:"priority,omitempty"`

	// RecurrenceConfig JSON configuration
	RecurrenceConfig  *string            `json:"recurrence_config,omitempty"`
	RecurrencePattern *RecurrencePattern `json:"recurrence_pattern,omitempty"`
	Tags              *[]string          `json:"tags,omitempty"`
	Title             *string            `json:"title,omitempty"`
	UpdatedAt         *time.Time         `json:"updated_at,omitempty"`
}

// TaskPriority defines model for TaskPriority.
type TaskPriority string

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TodoItem defines model for TodoItem.
type TodoItem struct {
	// ActualDuration ISO 8601 duration
	ActualDuration *string    `json:"actual_duration,omitempty"`
	CreateTime     *time.Time `json:"create_time,omitempty"`
	DueTime        *time.Time `json:"due_time,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration *string `json:"estimated_duration,omitempty"`

	// Etag Entity tag for optimistic concurrency control (RFC 7232). Quoted string format like "1", "2", etc.
	Etag                *string             `json:"etag,omitempty"`
	Id                  *openapi_types.UUID `json:"id,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *TaskPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`
	Status              *TaskStatus         `json:"status,omitempty"`
	Tags                *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone
	Timezone  *string    `json:"timezone,omitempty"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	CreateTime *time.Time          `json:"create_time,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Items      *[]TodoItem         `json:"items,omitempty"`
	Title      *string             `json:"title,omitempty"`

	// TotalItems Total items in this list
	TotalItems *int `json:"total_items,omitempty"`

	// UndoneItems Items not yet done
	UndoneItems *int `json:"undone_items,omitempty"`
}

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Item *TodoItem `json:"item,omitempty"`

	// UpdateMask Fields to update (field mask)
	UpdateMask *[]string `json:"update_mask,omitempty"`
}

// UpdateItemResponse defines model for UpdateItemResponse.
type UpdateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// UpdateRecurringTemplateRequest defines model for UpdateRecurringTemplateRequest.
type UpdateRecurringTemplateRequest struct {
	Template *RecurringTaskTemplate `json:"template,omitempty"`

	// UpdateMask Fields to update (field mask)
	UpdateMask *[]string `json:"update_mask,omitempty"`
}

// UpdateRecurringTemplateResponse defines model for UpdateRecurringTemplateResponse.
type UpdateRecurringTemplateResponse struct {
	Template *RecurringTaskTemplate `json:"template,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListListsParams defines parameters for ListLists.
type ListListsParams struct {
	// PageSize Number of lists per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Page token from previous response
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// TitleContains Filter by title substring (case-insensitive)
	TitleContains *string `form:"title_contains,omitempty" json:"title_contains,omitempty"`

	// CreatedAfter Filter lists created after this time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter lists created before this time
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`

	// SortBy Field to sort by
	SortBy *ListListsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir *ListListsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// ListListsParamsSortBy defines parameters for ListLists.
type ListListsParamsSortBy string

// ListListsParamsSortDir defines parameters for ListLists.
type ListListsParamsSortDir string

// ListRecurringTemplatesParams defines parameters for ListRecurringTemplates.
type ListRecurringTemplatesParams struct {
	// ActiveOnly Filter for active templates only
	ActiveOnly *bool `form:"active_only,omitempty" json:"active_only,omitempty"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	// Parent Optional parent list ID to filter by
	Parent *openapi_types.UUID `form:"parent,omitempty" json:"parent,omitempty"`

	// Status Filter by task status
	Status *ListTasksParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Priority Filter by task priority
	Priority *ListTasksParamsPriority `form:"priority,omitempty" json:"priority,omitempty"`

	// SortBy Field to sort by
	SortBy *ListTasksParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir   *ListTasksParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	PageSize  *int                    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string                 `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTasksParamsStatus defines parameters for ListTasks.
type ListTasksParamsStatus string

// ListTasksParamsPriority defines parameters for ListTasks.
type ListTasksParamsPriority string

// ListTasksParamsSortBy defines parameters for ListTasks.
type ListTasksParamsSortBy string

// ListTasksParamsSortDir defines parameters for ListTasks.
type ListTasksParamsSortDir string

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// CreateRecurringTemplateJSONRequestBody defines body for CreateRecurringTemplate for application/json ContentType.
type CreateRecurringTemplateJSONRequestBody = CreateRecurringTemplateRequest

// UpdateRecurringTemplateJSONRequestBody defines body for UpdateRecurringTemplate for application/json ContentType.
type UpdateRecurringTemplateJSONRequestBody = UpdateRecurringTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all todo lists with pagination
	// (GET /v1/lists)
	ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams)
	// Create a new todo list
	// (POST /v1/lists)
	CreateList(w http.ResponseWriter, r *http.Request)
	// Get a todo list by ID
	// (GET /v1/lists/{id})
	GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Create a new item in a list
	// (POST /v1/lists/{list_id}/items)
	CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Update an existing item
	// (PATCH /v1/lists/{list_id}/items/{item_id})
	UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID)
	// List recurring templates for a list
	// (GET /v1/lists/{list_id}/recurring-templates)
	ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams)
	// Create a recurring task template
	// (POST /v1/lists/{list_id}/recurring-templates)
	CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Delete a recurring template
	// (DELETE /v1/recurring-templates/{id})
	DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a recurring template by ID
	// (GET /v1/recurring-templates/{id})
	GetRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a recurring template
	// (PATCH /v1/recurring-templates/{id})
	UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Search tasks globally with filtering and sorting
	// (GET /v1/tasks)
	ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all todo lists with pagination
// (GET /v1/lists)
func (_ Unimplemented) ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new todo list
// (POST /v1/lists)
func (_ Unimplemented) CreateList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a todo list by ID
// (GET /v1/lists/{id})
func (_ Unimplemented) GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new item in a list
// (POST /v1/lists/{list_id}/items)
func (_ Unimplemented) CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing item
// (PATCH /v1/lists/{list_id}/items/{item_id})
func (_ Unimplemented) UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recurring templates for a list
// (GET /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a recurring task template
// (POST /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a recurring template
// (DELETE /v1/recurring-templates/{id})
func (_ Unimplemented) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a recurring template by ID
// (GET /v1/recurring-templates/{id})
func (_ Unimplemented) GetRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a recurring template
// (PATCH /v1/recurring-templates/{id})
func (_ Unimplemented) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search tasks globally with filtering and sorting
// (GET /v1/tasks)
func (_ Unimplemented) ListTasks(w http.ResponseWriter, r *http.Request, params ListTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListLists operation middleware
func (siw *ServerInterfaceWrapper) ListLists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListListsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "title_contains" -------------

	err = runtime.BindQueryParameter("form", true, false, "title_contains", r.URL.Query(), &params.TitleContains)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title_contains", Err: err})
		return
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateList operation middleware
func (siw *ServerInterfaceWrapper) CreateList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecurringTemplatesParams

	// ------------- Optional query parameter "active_only" -------------

	err = runtime.BindQueryParameter("form", true, false, "active_only", r.URL.Query(), &params.ActiveOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active_only", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringTemplates(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringTemplate(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecurringTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecurringTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringTemplate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTasks operation middleware
func (siw *ServerInterfaceWrapper) ListTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTasksParams

	// ------------- Optional query parameter "parent" -------------

	err = runtime.BindQueryParameter("form", true, false, "parent", r.URL.Query(), &params.Parent)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "parent", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameter("form", true, false, "priority", r.URL.Query(), &params.Priority)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "priority", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists", wrapper.ListLists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists", wrapper.CreateList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{id}", wrapper.GetList)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/items", wrapper.CreateItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/lists/{list_id}/items/{item_id}", wrapper.UpdateItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.ListRecurringTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.CreateRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/recurring-templates/{id}", wrapper.DeleteRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/recurring-templates/{id}", wrapper.GetRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/recurring-templates/{id}", wrapper.UpdateRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/tasks", wrapper.ListTasks)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RbX2/bOBL/KgTvgG0BNXaSdq/wW3b753LYtrmk+3BoA4OWRjbXFKmSo6Ru4O9+IClL",
	"VkTZShMnzfahiCyRnOH85W+GvaKxynIlQaKhoyuqweRKGnA/fmPJKXwpwKD9FSuJIN0jy3PBY4ZcycFf",
	"Rkn7zsQzyJh9+qeGlI7oPwb10gP/1Qxea630aUmELpfLiCZgYs1zuxgd0WN5wQRPiC4JLyN6LBG0ZMLN",
	"vU9OPFliQF+AJuDILyP6XuEbVcjk/lg5BaMKHQORCknqaC8j+qdkBc6U5t/gHnlZp0qeEV7qS2mScWO4",
	"nJKjk2MyhwW1c8tlLdXfNTCEY4RszahyrXLQyL3BJQWMkWdgn1OlM4Z0RBOG8My9jSgucqAjalBzObUy",
	"AIM8YwjJOCk08yxeXVfk2Qfy8tfhPqmGRBS+siwXdq2Tjwf/Phy+Cy3OpUEmYxhbFvrzlGuuNMfFNlF/",
	"ZGZ+shq7jKiGuNB2kTFClguGMOZJg2xR8CREEdnUyY8jZO6hPcK/YFozR8vy/k1JCEjr6P0RWX0mT2Bv",
	"uheRX14XVlGDM1TxfKZE9svThhCPMtA8ZoP3cDn+n9LzIJMchaOXsa9/gJzijI4OXryIaMbl6vd+a56T",
	"y5eCa2vjn8pFzqthavIXxC5KrJtXab0t+7Ly2aoVlSi7iiPdQeUPbrDTiKt91uI5m6k8t65hJ9JopxLw",
	"vHVJQHDP8jYJOEY3SOB0ZasfS1Pd6NMqTQ1gD88kfiRJtcrIyv2Ic787dP7WQlOQ4L+OL7lM1OU4YQvP",
	"PaSsEEhHh0OnNp4VGR0d/uqV5n/VKuMSYQr69kEAbNSJlUz5tL2l/5x9eE/8R5IqTXKGNlM9MznEPOUx",
	"MYDI5dSEtrq2fjlvG4en1YyTcsJ3Rpw7c//gLs5vYqtd7rEKvP1kYpdkZr5aNuwvzYTaogirQ03zdawS",
	"CIo1AWRcNGXfnJpyEElwLjemCK0aYvu6+jIwhk37zQ6t9xZw15HpLeDDqtqyZv+ZzbtsKq/fftsKkfAV",
	"xzmbwhjVHGRPtXodXBOS2S6l/jx3yOv6BrqYs7PM5gx+M/n5XH5X8msHQ+vD0qaBTzRhXCxoRC8B5u5h",
	"wqvHTEmcuacFMO0evhRMI+hqiss554GYHRZpO2a4aJeMGfY/q94oOz9QDm4n157HYm7GLEZ+sR61JkoJ",
	"YC6HCWZwXJKFZFxI5KK/5Kwn9z2f389hYINwHz7rt0YWeXJDaw35Y0Nia64o1KV1Okh4kdGIzvh0RiNa",
	"6KkFyCEfswudIcPCrC+DKlHUAsFxrtVUg7FnqolQ8RysohOLoCLKdDzjF+5NbA+sQkASJrKKRy3fZTEW",
	"TNzWh3wEuCGEvj/Q3V4IWcCkX0vkuCDI/PFW5cgzbpDH1s5Lq1zYZ9RKkCenb34n/zo4PHi6R/5bKISE",
	"eALEb4YIPgfyme5/phH5TA/sH8B4LxgwesaVx1IXMJVBb6NXmv4uawkbawK7Cg+rA1RHsryh4fe1jzs7",
	"pHTLBxUyMa4INOX+0X4k7iPhkuCMGyJ86aGdTAtpw1jXUsduEamQLABJ0tBjtUhI9H86BW4s992sHLOy",
	"iXHGzLzN6BsLewxBRfww8sQBIWJHN4pVNYos3WPNM8+j3na/bc+7q0F5Kv0rMLdEOreU++3l+ZCgzgZR",
	"O5bj4szOLRsjwDToowJnbXmU1W+SM2MgIcwQP5o4mGHd8aisn/uK1wxYApqWpXJ3RHXjazebIea+Es9l",
	"qtoUT1+ffUwL4eruNmEiM3PCZOJcnmRMsilkIJFccpyRKpuQGttVgYa+U1IRKxTyrp53dHJMI3oB2niC",
	"+3vDvaHVj8pBspzTET3cG+4dWk9iOHMiGlzsDyqwO/XwwmrKbfo4oaMaLbtpmmWAoA0dfbq+v/dFNgFN",
	"VOo2ZEgOmljg5g5mdES/FKAthpLMic9hOsO/wUqmrFHIO1gv5O0Ph5sLecvoOjcnbAqlLl2VMtdwwVVh",
	"yKp1toktDzXX+WolsbZ/CQRNJgvidERMMSnPN09iZuAZlwak4RbmPO0g7SZaBIGMS/Nd5L3kS4RJWGrf",
	"ubRSpsoQ2QqP2tENqv3SeS9WJpAqDb158cPvhBkb5FARozSSyaKDrv06dl8Dptg4hEQV6Gi+vV7v72bp",
	"zHKScA1xed7uZCjhuoMju+IaK8z9ci8DHJxHzX7xwXB4Z33Idi0t0It0A4gG1Bwu7MG/iGMwJi2EcMen",
	"556hEJ2K8cFal9tN2d8+pdF5XUb0RR86zTa2yyxFljG9KDdCmBDEAs7Swl20ztmUywo/uaP5J79tem4h",
	"hTKByFo3gqgvn4PB31SyuDPltLtgy2alHnUBy5Z17O+Egc3mUQWKR2sbfq+EEQmXtX0EzGEZ1Vl3cMWT",
	"ZWfqLYvx2xKvk9/xq1Uksbm9DiQO+jQ1HoyqYZC009hxvdfQZRrVTYrvUuzz4fPtk6q7IndhCW8BCatN",
	"wJ4JnHY2G0JZqFwO6n7RhqjhYMdt7GJVF721cewqbK1D0gcJWw18GLp4hJA9eNi6f+tuxDlrqxYrsevB",
	"ztUjttj44Mr+GZcRMGcYz9rmXmP1Bzf3KFR06Q68fm8/ooO1az69HGy4Ewa2OFhZYPyJHMwLhzBJ4Cs3",
	"aCEk9+bf07mq0sGzRlu4E923G80/nquVoDJVmvheYV0WIUqKLlznx47LEQEklTJhIGp1HXeOmTY09wOe",
	"UA3aCKIehXU70wkUt7xqr6eRgGluw1OtKX/vY1JnfflBzkzdNeANVv0zH6LWPIGZeeUO21ygjPyBSF8h",
	"ygQE+Ap700teufc39pJKWfcGNJ8HGmYrJvzmHm0Q9Dpoqr+n5qPOUsEjUOmd1g6+L9Y8zmJC205aVYWu",
	"VLkJVv2YJrMrwHO7VDncPTc9zPfnhUPfESvLLGkz62YE5G6zbrP9D+6BCZIzDRJ9be/4FUFF0lXzr7Op",
	"aGfQu0BAk4U/KVSXIoLdo9XHmt5Orspt5bK6sdEhl/pzm9Mb3g3cae/PXXCq+23VXbxofQuNoWsXo37I",
	"pmB0dT9d+Vv02HeNwZt32ENR1w74O/Qtz8A6tHNJQ6ZCTZgQC9+59KHLRlUmE+cpVvh1YPWh8Xy5fsXG",
	"Bcf1yzWfzq2y/H/ADUJsFTNBErgAofLMh8JCi/LSzGgwEHbATBkcvRy+3B+wnNPl+fL/AQAA//9GPaoy",
	"9jwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
