// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type TodoItem struct {
	ID         string         `json:"id"`
	ListID     string         `json:"list_id"`
	Title      string         `json:"title"`
	Completed  int32          `json:"completed"`
	CreateTime time.Time      `json:"create_time"`
	DueTime    sql.NullTime   `json:"due_time"`
	Tags       sql.NullString `json:"tags"`
}

type TodoList struct {
	ID         string    `json:"id"`
	Title      string    `json:"title"`
	CreateTime time.Time `json:"create_time"`
}
