// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateTodoItem(ctx context.Context, arg CreateTodoItemParams) error
	CreateTodoList(ctx context.Context, arg CreateTodoListParams) error
	DeleteTodoItem(ctx context.Context, arg DeleteTodoItemParams) error
	DeleteTodoItemsByListId(ctx context.Context, listID string) error
	DeleteTodoList(ctx context.Context, id string) error
	GetTodoItemsByListId(ctx context.Context, listID string) ([]TodoItem, error)
	GetTodoList(ctx context.Context, id string) (TodoList, error)
	ListTodoLists(ctx context.Context) ([]TodoList, error)
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) error
}

var _ Querier = (*Queries)(nil)
