// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) error
	CreateRecurringTemplate(ctx context.Context, arg CreateRecurringTemplateParams) error
	CreateStatusHistoryEntry(ctx context.Context, arg CreateStatusHistoryEntryParams) error
	CreateTodoItem(ctx context.Context, arg CreateTodoItemParams) error
	CreateTodoList(ctx context.Context, arg CreateTodoListParams) error
	DeactivateAPIKey(ctx context.Context, id uuid.UUID) error
	DeactivateRecurringTemplate(ctx context.Context, arg DeactivateRecurringTemplateParams) error
	DeleteCompletedGenerationJobs(ctx context.Context, completedAt sql.NullTime) error
	DeleteRecurringTemplate(ctx context.Context, id uuid.UUID) error
	DeleteTodoItem(ctx context.Context, id uuid.UUID) error
	DeleteTodoItemsByListId(ctx context.Context, listID uuid.UUID) error
	DeleteTodoList(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByShortToken(ctx context.Context, shortToken string) (ApiKey, error)
	GetAllTodoItems(ctx context.Context) ([]TodoItem, error)
	GetGenerationJob(ctx context.Context, id uuid.UUID) (RecurringGenerationJob, error)
	GetRecurringTemplate(ctx context.Context, id uuid.UUID) (RecurringTaskTemplate, error)
	GetTaskStatusHistory(ctx context.Context, taskID uuid.UUID) ([]TaskStatusHistory, error)
	GetTaskStatusHistoryByDateRange(ctx context.Context, arg GetTaskStatusHistoryByDateRangeParams) ([]TaskStatusHistory, error)
	GetTodoItem(ctx context.Context, id uuid.UUID) (TodoItem, error)
	GetTodoItemsByListId(ctx context.Context, listID uuid.UUID) ([]TodoItem, error)
	GetTodoList(ctx context.Context, id uuid.UUID) (TodoList, error)
	ListActiveAPIKeys(ctx context.Context) ([]ApiKey, error)
	ListAllActiveRecurringTemplates(ctx context.Context) ([]RecurringTaskTemplate, error)
	ListAllRecurringTemplatesByList(ctx context.Context, listID uuid.UUID) ([]RecurringTaskTemplate, error)
	ListPendingGenerationJobs(ctx context.Context, arg ListPendingGenerationJobsParams) ([]RecurringGenerationJob, error)
	ListRecurringTemplates(ctx context.Context, listID uuid.UUID) ([]RecurringTaskTemplate, error)
	// Optimized for SEARCH/FILTER access pattern: Database-level filtering, sorting, and pagination.
	// Performance: Pushes all operations to PostgreSQL with proper indexes vs loading all items to memory.
	// Use case: Task search, filtered views, "My Tasks" views, pagination through large result sets.
	//
	// Parameters (use zero values for NULL to skip filters):
	//   $1: list_id     - Filter by specific list (zero UUID to search all lists)
	//   $2: status      - Filter by status (empty string to skip)
	//   $3: priority    - Filter by priority (empty string to skip)
	//   $4: tag         - Filter by tag (JSONB array contains, empty string to skip)
	//   $5: due_before  - Filter tasks due before timestamp (zero time to skip)
	//   $6: due_after   - Filter tasks due after timestamp (zero time to skip)
	//   $7: updated_at  - Filter by last update time (zero time to skip)
	//   $8: created_at  - Filter by creation time (zero time to skip)
	//   $9: order_by    - Sort field: 'due_time', 'priority', 'created_at', 'updated_at'
	//   $10: limit      - Page size (max items to return)
	//   $11: offset     - Pagination offset (skip N items)
	//
	// Access pattern example:
	//   - "Show my overdue tasks": filter by due_before=now, order by due_time
	//   - "Tasks in List X": filter by list_id, default sort
	//   - "High priority items": filter by priority=HIGH, order by due_time
	//   - "Tasks tagged 'urgent'": filter by tag=urgent (uses GIN index)
	ListTasksWithFilters(ctx context.Context, arg ListTasksWithFiltersParams) ([]TodoItem, error)
	// Legacy query: Returns all lists without items (use ListTodoListsWithCounts for list views).
	ListTodoLists(ctx context.Context) ([]TodoList, error)
	// Optimized for LIST VIEW access pattern: Returns list metadata with item counts.
	// Performance: O(lists + items) with single aggregation query vs O(lists * items) loading all items.
	// Use case: Dashboard/overview pages showing list summaries without loading full item details.
	//
	// Returns:
	//   - total_items: Total count of all items in the list
	//   - undone_items: Count of active items (TODO, IN_PROGRESS, BLOCKED)
	//
	// This query uses LEFT JOIN to ensure lists with zero items still appear with count=0.
	// The FILTER clause efficiently counts only active items in a single pass.
	ListTodoListsWithCounts(ctx context.Context) ([]ListTodoListsWithCountsRow, error)
	UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error
	UpdateGenerationJobStatus(ctx context.Context, arg UpdateGenerationJobStatusParams) error
	UpdateRecurringTemplate(ctx context.Context, arg UpdateRecurringTemplateParams) error
	UpdateRecurringTemplateGenerationWindow(ctx context.Context, arg UpdateRecurringTemplateGenerationWindowParams) error
	UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) error
	UpdateTodoItemStatus(ctx context.Context, arg UpdateTodoItemStatusParams) error
	UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) error
}

var _ Querier = (*Queries)(nil)
