// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: todo_lists.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTodoList = `-- name: CreateTodoList :exec
INSERT INTO todo_lists (id, title, create_time)
VALUES ($1, $2, $3)
`

type CreateTodoListParams struct {
	ID         string    `json:"id"`
	Title      string    `json:"title"`
	CreateTime time.Time `json:"create_time"`
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) error {
	_, err := q.db.ExecContext(ctx, createTodoList, arg.ID, arg.Title, arg.CreateTime)
	return err
}

const deleteTodoList = `-- name: DeleteTodoList :exec
DELETE FROM todo_lists
WHERE id = $1
`

func (q *Queries) DeleteTodoList(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodoList, id)
	return err
}

const getTodoList = `-- name: GetTodoList :one
SELECT id, title, create_time
FROM todo_lists
WHERE id = $1
`

func (q *Queries) GetTodoList(ctx context.Context, id string) (TodoList, error) {
	row := q.db.QueryRowContext(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(&i.ID, &i.Title, &i.CreateTime)
	return i, err
}

const listTodoLists = `-- name: ListTodoLists :many
SELECT id, title, create_time
FROM todo_lists
ORDER BY create_time DESC
`

func (q *Queries) ListTodoLists(ctx context.Context) ([]TodoList, error) {
	rows, err := q.db.QueryContext(ctx, listTodoLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoList{}
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(&i.ID, &i.Title, &i.CreateTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoList = `-- name: UpdateTodoList :exec
UPDATE todo_lists
SET title = $1, create_time = $2
WHERE id = $3
`

type UpdateTodoListParams struct {
	Title      string    `json:"title"`
	CreateTime time.Time `json:"create_time"`
	ID         string    `json:"id"`
}

func (q *Queries) UpdateTodoList(ctx context.Context, arg UpdateTodoListParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoList, arg.Title, arg.CreateTime, arg.ID)
	return err
}
