// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mono/v1/mono.proto

package monov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	DueTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=due_time,json=dueTime,proto3" json:"due_time,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoItem) Reset() {
	*x = TodoItem{}
	mi := &file_mono_v1_mono_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoItem) ProtoMessage() {}

func (x *TodoItem) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoItem.ProtoReflect.Descriptor instead.
func (*TodoItem) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{0}
}

func (x *TodoItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TodoItem) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *TodoItem) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *TodoItem) GetDueTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DueTime
	}
	return nil
}

func (x *TodoItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TodoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Items         []*TodoItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoList) Reset() {
	*x = TodoList{}
	mi := &file_mono_v1_mono_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoList) ProtoMessage() {}

func (x *TodoList) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoList.ProtoReflect.Descriptor instead.
func (*TodoList) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{1}
}

func (x *TodoList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TodoList) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TodoList) GetItems() []*TodoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TodoList) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type CreateListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListRequest) Reset() {
	*x = CreateListRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListRequest) ProtoMessage() {}

func (x *CreateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListRequest.ProtoReflect.Descriptor instead.
func (*CreateListRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{2}
}

func (x *CreateListRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *TodoList              `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListResponse) Reset() {
	*x = CreateListResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListResponse) ProtoMessage() {}

func (x *CreateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListResponse.ProtoReflect.Descriptor instead.
func (*CreateListResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{3}
}

func (x *CreateListResponse) GetList() *TodoList {
	if x != nil {
		return x.List
	}
	return nil
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{4}
}

func (x *GetListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          *TodoList              `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{5}
}

func (x *GetListResponse) GetList() *TodoList {
	if x != nil {
		return x.List
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DueTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_time,json=dueTime,proto3" json:"due_time,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{6}
}

func (x *CreateItemRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *CreateItemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateItemRequest) GetDueTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DueTime
	}
	return nil
}

func (x *CreateItemRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TodoItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{7}
}

func (x *CreateItemResponse) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        string                 `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	Item          *TodoItem              `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateItemRequest) GetListId() string {
	if x != nil {
		return x.ListId
	}
	return ""
}

func (x *UpdateItemRequest) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *UpdateItemRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *TodoItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateItemResponse) GetItem() *TodoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListListsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListsRequest) Reset() {
	*x = ListListsRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListsRequest) ProtoMessage() {}

func (x *ListListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListsRequest.ProtoReflect.Descriptor instead.
func (*ListListsRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{10}
}

type ListListsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         []*TodoList            `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListsResponse) Reset() {
	*x = ListListsResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListsResponse) ProtoMessage() {}

func (x *ListListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListsResponse.ProtoReflect.Descriptor instead.
func (*ListListsResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{11}
}

func (x *ListListsResponse) GetLists() []*TodoList {
	if x != nil {
		return x.Lists
	}
	return nil
}

type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Parent list to filter by. If empty, search globally.
	Parent    string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// AIP-160 filtering (e.g. "manual filter").
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// AIP-132 sorting (e.g. "create_time desc").
	OrderBy       string `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_mono_v1_mono_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{12}
}

func (x *ListTasksRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListTasksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListTasksRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TodoItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_mono_v1_mono_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mono_v1_mono_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_mono_v1_mono_proto_rawDescGZIP(), []int{13}
}

func (x *ListTasksResponse) GetItems() []*TodoItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListTasksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_mono_v1_mono_proto protoreflect.FileDescriptor

const file_mono_v1_mono_proto_rawDesc = "" +
	"\n" +
	"\x12mono/v1/mono.proto\x12\amono.v1\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xdf\x01\n" +
	"\bTodoItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x125\n" +
	"\bdue_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueTime\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"\x9f\x01\n" +
	"\bTodoList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.mono.v1.TodoItemR\x05items\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"2\n" +
	"\x11CreateListRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\";\n" +
	"\x12CreateListResponse\x12%\n" +
	"\x04list\x18\x01 \x01(\v2\x11.mono.v1.TodoListR\x04list\")\n" +
	"\x0eGetListRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"8\n" +
	"\x0fGetListResponse\x12%\n" +
	"\x04list\x18\x01 \x01(\v2\x11.mono.v1.TodoListR\x04list\"\x9f\x01\n" +
	"\x11CreateItemRequest\x12 \n" +
	"\alist_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06listId\x12\x1d\n" +
	"\x05title\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05title\x125\n" +
	"\bdue_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\adueTime\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\";\n" +
	"\x12CreateItemResponse\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x11.mono.v1.TodoItemR\x04item\"\xa1\x01\n" +
	"\x11UpdateItemRequest\x12 \n" +
	"\alist_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06listId\x12-\n" +
	"\x04item\x18\x02 \x01(\v2\x11.mono.v1.TodoItemB\x06\xbaH\x03\xc8\x01\x01R\x04item\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\";\n" +
	"\x12UpdateItemResponse\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x11.mono.v1.TodoItemR\x04item\"\x12\n" +
	"\x10ListListsRequest\"<\n" +
	"\x11ListListsResponse\x12'\n" +
	"\x05lists\x18\x01 \x03(\v2\x11.mono.v1.TodoListR\x05lists\"\x99\x01\n" +
	"\x10ListTasksRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x05 \x01(\tR\aorderBy\"d\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.mono.v1.TodoItemR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xd2\x04\n" +
	"\vMonoService\x12[\n" +
	"\n" +
	"CreateList\x12\x1a.mono.v1.CreateListRequest\x1a\x1b.mono.v1.CreateListResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/lists\x12T\n" +
	"\aGetList\x12\x17.mono.v1.GetListRequest\x1a\x18.mono.v1.GetListResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/lists/{id}\x12k\n" +
	"\n" +
	"CreateItem\x12\x1a.mono.v1.CreateItemRequest\x1a\x1b.mono.v1.CreateItemResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/lists/{list_id}/items\x12u\n" +
	"\n" +
	"UpdateItem\x12\x1a.mono.v1.UpdateItemRequest\x1a\x1b.mono.v1.UpdateItemResponse\".\x82\xd3\xe4\x93\x02(:\x01*2#/v1/lists/{list_id}/items/{item.id}\x12U\n" +
	"\tListLists\x12\x19.mono.v1.ListListsRequest\x1a\x1a.mono.v1.ListListsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/lists\x12U\n" +
	"\tListTasks\x12\x19.mono.v1.ListTasksRequest\x1a\x1a.mono.v1.ListTasksResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasksB1Z/github.com/rezkam/mono/api/proto/mono/v1;monov1b\x06proto3"

var (
	file_mono_v1_mono_proto_rawDescOnce sync.Once
	file_mono_v1_mono_proto_rawDescData []byte
)

func file_mono_v1_mono_proto_rawDescGZIP() []byte {
	file_mono_v1_mono_proto_rawDescOnce.Do(func() {
		file_mono_v1_mono_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mono_v1_mono_proto_rawDesc), len(file_mono_v1_mono_proto_rawDesc)))
	})
	return file_mono_v1_mono_proto_rawDescData
}

var file_mono_v1_mono_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mono_v1_mono_proto_goTypes = []any{
	(*TodoItem)(nil),              // 0: mono.v1.TodoItem
	(*TodoList)(nil),              // 1: mono.v1.TodoList
	(*CreateListRequest)(nil),     // 2: mono.v1.CreateListRequest
	(*CreateListResponse)(nil),    // 3: mono.v1.CreateListResponse
	(*GetListRequest)(nil),        // 4: mono.v1.GetListRequest
	(*GetListResponse)(nil),       // 5: mono.v1.GetListResponse
	(*CreateItemRequest)(nil),     // 6: mono.v1.CreateItemRequest
	(*CreateItemResponse)(nil),    // 7: mono.v1.CreateItemResponse
	(*UpdateItemRequest)(nil),     // 8: mono.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil),    // 9: mono.v1.UpdateItemResponse
	(*ListListsRequest)(nil),      // 10: mono.v1.ListListsRequest
	(*ListListsResponse)(nil),     // 11: mono.v1.ListListsResponse
	(*ListTasksRequest)(nil),      // 12: mono.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 13: mono.v1.ListTasksResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 15: google.protobuf.FieldMask
}
var file_mono_v1_mono_proto_depIdxs = []int32{
	14, // 0: mono.v1.TodoItem.create_time:type_name -> google.protobuf.Timestamp
	14, // 1: mono.v1.TodoItem.due_time:type_name -> google.protobuf.Timestamp
	0,  // 2: mono.v1.TodoList.items:type_name -> mono.v1.TodoItem
	14, // 3: mono.v1.TodoList.create_time:type_name -> google.protobuf.Timestamp
	1,  // 4: mono.v1.CreateListResponse.list:type_name -> mono.v1.TodoList
	1,  // 5: mono.v1.GetListResponse.list:type_name -> mono.v1.TodoList
	14, // 6: mono.v1.CreateItemRequest.due_time:type_name -> google.protobuf.Timestamp
	0,  // 7: mono.v1.CreateItemResponse.item:type_name -> mono.v1.TodoItem
	0,  // 8: mono.v1.UpdateItemRequest.item:type_name -> mono.v1.TodoItem
	15, // 9: mono.v1.UpdateItemRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 10: mono.v1.UpdateItemResponse.item:type_name -> mono.v1.TodoItem
	1,  // 11: mono.v1.ListListsResponse.lists:type_name -> mono.v1.TodoList
	0,  // 12: mono.v1.ListTasksResponse.items:type_name -> mono.v1.TodoItem
	2,  // 13: mono.v1.MonoService.CreateList:input_type -> mono.v1.CreateListRequest
	4,  // 14: mono.v1.MonoService.GetList:input_type -> mono.v1.GetListRequest
	6,  // 15: mono.v1.MonoService.CreateItem:input_type -> mono.v1.CreateItemRequest
	8,  // 16: mono.v1.MonoService.UpdateItem:input_type -> mono.v1.UpdateItemRequest
	10, // 17: mono.v1.MonoService.ListLists:input_type -> mono.v1.ListListsRequest
	12, // 18: mono.v1.MonoService.ListTasks:input_type -> mono.v1.ListTasksRequest
	3,  // 19: mono.v1.MonoService.CreateList:output_type -> mono.v1.CreateListResponse
	5,  // 20: mono.v1.MonoService.GetList:output_type -> mono.v1.GetListResponse
	7,  // 21: mono.v1.MonoService.CreateItem:output_type -> mono.v1.CreateItemResponse
	9,  // 22: mono.v1.MonoService.UpdateItem:output_type -> mono.v1.UpdateItemResponse
	11, // 23: mono.v1.MonoService.ListLists:output_type -> mono.v1.ListListsResponse
	13, // 24: mono.v1.MonoService.ListTasks:output_type -> mono.v1.ListTasksResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_mono_v1_mono_proto_init() }
func file_mono_v1_mono_proto_init() {
	if File_mono_v1_mono_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mono_v1_mono_proto_rawDesc), len(file_mono_v1_mono_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mono_v1_mono_proto_goTypes,
		DependencyIndexes: file_mono_v1_mono_proto_depIdxs,
		MessageInfos:      file_mono_v1_mono_proto_msgTypes,
	}.Build()
	File_mono_v1_mono_proto = out.File
	file_mono_v1_mono_proto_goTypes = nil
	file_mono_v1_mono_proto_depIdxs = nil
}
