// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ItemPriority.
const (
	ItemPriorityHigh   ItemPriority = "high"
	ItemPriorityLow    ItemPriority = "low"
	ItemPriorityMedium ItemPriority = "medium"
	ItemPriorityUrgent ItemPriority = "urgent"
)

// Defines values for ItemStatus.
const (
	ItemStatusArchived   ItemStatus = "archived"
	ItemStatusBlocked    ItemStatus = "blocked"
	ItemStatusCancelled  ItemStatus = "cancelled"
	ItemStatusDone       ItemStatus = "done"
	ItemStatusInProgress ItemStatus = "in_progress"
	ItemStatusTodo       ItemStatus = "todo"
)

// Defines values for RecurrencePattern.
const (
	Biweekly  RecurrencePattern = "biweekly"
	Daily     RecurrencePattern = "daily"
	Monthly   RecurrencePattern = "monthly"
	Quarterly RecurrencePattern = "quarterly"
	Weekdays  RecurrencePattern = "weekdays"
	Weekly    RecurrencePattern = "weekly"
	Yearly    RecurrencePattern = "yearly"
)

// Defines values for UpdateItemRequestUpdateMask.
const (
	UpdateItemRequestUpdateMaskActualDuration    UpdateItemRequestUpdateMask = "actual_duration"
	UpdateItemRequestUpdateMaskDueAt             UpdateItemRequestUpdateMask = "due_at"
	UpdateItemRequestUpdateMaskDueOffset         UpdateItemRequestUpdateMask = "due_offset"
	UpdateItemRequestUpdateMaskEstimatedDuration UpdateItemRequestUpdateMask = "estimated_duration"
	UpdateItemRequestUpdateMaskPriority          UpdateItemRequestUpdateMask = "priority"
	UpdateItemRequestUpdateMaskStartsAt          UpdateItemRequestUpdateMask = "starts_at"
	UpdateItemRequestUpdateMaskStatus            UpdateItemRequestUpdateMask = "status"
	UpdateItemRequestUpdateMaskTags              UpdateItemRequestUpdateMask = "tags"
	UpdateItemRequestUpdateMaskTimezone          UpdateItemRequestUpdateMask = "timezone"
	UpdateItemRequestUpdateMaskTitle             UpdateItemRequestUpdateMask = "title"
)

// Defines values for UpdateRecurringTemplateRequestUpdateMask.
const (
	UpdateRecurringTemplateRequestUpdateMaskDueOffset             UpdateRecurringTemplateRequestUpdateMask = "due_offset"
	UpdateRecurringTemplateRequestUpdateMaskEstimatedDuration     UpdateRecurringTemplateRequestUpdateMask = "estimated_duration"
	UpdateRecurringTemplateRequestUpdateMaskGenerationHorizonDays UpdateRecurringTemplateRequestUpdateMask = "generation_horizon_days"
	UpdateRecurringTemplateRequestUpdateMaskIsActive              UpdateRecurringTemplateRequestUpdateMask = "is_active"
	UpdateRecurringTemplateRequestUpdateMaskPriority              UpdateRecurringTemplateRequestUpdateMask = "priority"
	UpdateRecurringTemplateRequestUpdateMaskRecurrenceConfig      UpdateRecurringTemplateRequestUpdateMask = "recurrence_config"
	UpdateRecurringTemplateRequestUpdateMaskRecurrencePattern     UpdateRecurringTemplateRequestUpdateMask = "recurrence_pattern"
	UpdateRecurringTemplateRequestUpdateMaskSyncHorizonDays       UpdateRecurringTemplateRequestUpdateMask = "sync_horizon_days"
	UpdateRecurringTemplateRequestUpdateMaskTags                  UpdateRecurringTemplateRequestUpdateMask = "tags"
	UpdateRecurringTemplateRequestUpdateMaskTitle                 UpdateRecurringTemplateRequestUpdateMask = "title"
)

// Defines values for ListListsParamsSortBy.
const (
	ListListsParamsSortByCreatedAt ListListsParamsSortBy = "created_at"
	ListListsParamsSortByTitle     ListListsParamsSortBy = "title"
)

// Defines values for ListListsParamsSortDir.
const (
	ListListsParamsSortDirAsc  ListListsParamsSortDir = "asc"
	ListListsParamsSortDirDesc ListListsParamsSortDir = "desc"
)

// Defines values for ListItemsParamsStatus.
const (
	ListItemsParamsStatusArchived   ListItemsParamsStatus = "archived"
	ListItemsParamsStatusBlocked    ListItemsParamsStatus = "blocked"
	ListItemsParamsStatusCancelled  ListItemsParamsStatus = "cancelled"
	ListItemsParamsStatusDone       ListItemsParamsStatus = "done"
	ListItemsParamsStatusInProgress ListItemsParamsStatus = "in_progress"
	ListItemsParamsStatusTodo       ListItemsParamsStatus = "todo"
)

// Defines values for ListItemsParamsPriority.
const (
	ListItemsParamsPriorityHigh   ListItemsParamsPriority = "high"
	ListItemsParamsPriorityLow    ListItemsParamsPriority = "low"
	ListItemsParamsPriorityMedium ListItemsParamsPriority = "medium"
	ListItemsParamsPriorityUrgent ListItemsParamsPriority = "urgent"
)

// Defines values for ListItemsParamsSortBy.
const (
	ListItemsParamsSortByCreatedAt ListItemsParamsSortBy = "created_at"
	ListItemsParamsSortByDueAt     ListItemsParamsSortBy = "due_at"
	ListItemsParamsSortByPriority  ListItemsParamsSortBy = "priority"
	ListItemsParamsSortByUpdatedAt ListItemsParamsSortBy = "updated_at"
)

// Defines values for ListItemsParamsSortDir.
const (
	ListItemsParamsSortDirAsc  ListItemsParamsSortDir = "asc"
	ListItemsParamsSortDirDesc ListItemsParamsSortDir = "desc"
)

// CreateItemRequest defines model for CreateItemRequest.
type CreateItemRequest struct {
	DueAt *time.Time `json:"due_at,omitempty"`

	// DueOffset Duration from starts_at to due_at (ISO 8601 duration).
	// If set with starts_at, due_at = starts_at + due_offset.
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration   *string             `json:"estimated_duration,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *ItemPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`

	// StartsAt When the task becomes active/visible.
	// For recurring items: set from the occurrence pattern.
	// For direct items: explicitly set to schedule future tasks.
	StartsAt *openapi_types.Date `json:"starts_at,omitempty"`
	Status   *ItemStatus         `json:"status,omitempty"`
	Tags     *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone (e.g., 'Europe/Stockholm')
	Timezone *string `json:"timezone,omitempty"`
	Title    string  `json:"title"`
}

// CreateItemResponse defines model for CreateItemResponse.
type CreateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// CreateListRequest defines model for CreateListRequest.
type CreateListRequest struct {
	Title string `json:"title"`
}

// CreateListResponse defines model for CreateListResponse.
type CreateListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// CreateRecurringTemplateRequest defines model for CreateRecurringTemplateRequest.
type CreateRecurringTemplateRequest struct {
	// DueOffset ISO 8601 duration offset from instance date
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration *string `json:"estimated_duration,omitempty"`

	// GenerationHorizonDays Total generation horizon (ASYNC layer)
	GenerationHorizonDays *int          `json:"generation_horizon_days,omitempty"`
	Priority              *ItemPriority `json:"priority,omitempty"`

	// RecurrenceConfig JSON config for pattern-specific settings
	RecurrenceConfig  *string           `json:"recurrence_config,omitempty"`
	RecurrencePattern RecurrencePattern `json:"recurrence_pattern"`

	// SyncHorizonDays Days to generate immediately (SYNC layer)
	SyncHorizonDays *int      `json:"sync_horizon_days,omitempty"`
	Tags            *[]string `json:"tags,omitempty"`
	Title           string    `json:"title"`
}

// CreateRecurringTemplateResponse defines model for CreateRecurringTemplateResponse.
type CreateRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// DeadLetterJob defines model for DeadLetterJob.
type DeadLetterJob struct {
	ErrorMessage  *string             `json:"error_message,omitempty"`
	ErrorType     *string             `json:"error_type,omitempty"`
	FailedAt      *time.Time          `json:"failed_at,omitempty"`
	GenerateFrom  *time.Time          `json:"generate_from,omitempty"`
	GenerateUntil *time.Time          `json:"generate_until,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	LastWorkerId  *string             `json:"last_worker_id,omitempty"`
	OriginalJobId *openapi_types.UUID `json:"original_job_id,omitempty"`
	RetryCount    *int                `json:"retry_count,omitempty"`
	TemplateId    *openapi_types.UUID `json:"template_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *struct {
		Code    *string `json:"code,omitempty"`
		Details *[]struct {
			Field *string `json:"field,omitempty"`
			Issue *string `json:"issue,omitempty"`
		} `json:"details,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"error,omitempty"`
}

// GetListResponse defines model for GetListResponse.
type GetListResponse struct {
	List *TodoList `json:"list,omitempty"`
}

// GetRecurringTemplateResponse defines model for GetRecurringTemplateResponse.
type GetRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// ItemPriority defines model for ItemPriority.
type ItemPriority string

// ItemStatus defines model for ItemStatus.
type ItemStatus string

// ListDeadLetterJobsResponse defines model for ListDeadLetterJobsResponse.
type ListDeadLetterJobsResponse struct {
	Jobs *[]DeadLetterJob `json:"jobs,omitempty"`
}

// ListItemsResponse defines model for ListItemsResponse.
type ListItemsResponse struct {
	Items         *[]TodoItem `json:"items,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// ListListsResponse defines model for ListListsResponse.
type ListListsResponse struct {
	Lists         *[]TodoList `json:"lists,omitempty"`
	NextPageToken *string     `json:"next_page_token,omitempty"`
}

// ListRecurringTemplatesResponse defines model for ListRecurringTemplatesResponse.
type ListRecurringTemplatesResponse struct {
	Templates *[]RecurringItemTemplate `json:"templates,omitempty"`
}

// RecurrencePattern defines model for RecurrencePattern.
type RecurrencePattern string

// RecurringItemTemplate defines model for RecurringItemTemplate.
type RecurringItemTemplate struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DueOffset ISO 8601 duration
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration *string `json:"estimated_duration,omitempty"`

	// GenerationHorizonDays Total generation horizon in days (ASYNC layer)
	GenerationHorizonDays *int                `json:"generation_horizon_days,omitempty"`
	Id                    *openapi_types.UUID `json:"id,omitempty"`
	IsActive              *bool               `json:"is_active,omitempty"`
	LastGeneratedUntil    *time.Time          `json:"last_generated_until,omitempty"`
	ListId                *openapi_types.UUID `json:"list_id,omitempty"`
	Priority              *ItemPriority       `json:"priority,omitempty"`

	// RecurrenceConfig JSON configuration
	RecurrenceConfig  *string            `json:"recurrence_config,omitempty"`
	RecurrencePattern *RecurrencePattern `json:"recurrence_pattern,omitempty"`

	// SyncHorizonDays Days to generate immediately on create/update (SYNC layer)
	SyncHorizonDays *int       `json:"sync_horizon_days,omitempty"`
	Tags            *[]string  `json:"tags,omitempty"`
	Title           *string    `json:"title,omitempty"`
	UpdatedAt       *time.Time `json:"updated_at,omitempty"`
}

// RetryDeadLetterJobResponse defines model for RetryDeadLetterJobResponse.
type RetryDeadLetterJobResponse struct {
	NewJobId *openapi_types.UUID `json:"new_job_id,omitempty"`
}

// TodoItem defines model for TodoItem.
type TodoItem struct {
	// ActualDuration ISO 8601 duration
	ActualDuration *string    `json:"actual_duration,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DueAt          *time.Time `json:"due_at,omitempty"`

	// DueOffset Duration from starts_at to due_at (ISO 8601 duration).
	// If set with starts_at, due_at = starts_at + due_offset.
	DueOffset *string `json:"due_offset,omitempty"`

	// EstimatedDuration ISO 8601 duration
	EstimatedDuration *string `json:"estimated_duration,omitempty"`

	// Etag Entity tag for optimistic concurrency control (RFC 7232). Quoted string format like "1", "2", etc.
	Etag                *string             `json:"etag,omitempty"`
	Id                  *openapi_types.UUID `json:"id,omitempty"`
	InstanceDate        *time.Time          `json:"instance_date,omitempty"`
	Priority            *ItemPriority       `json:"priority,omitempty"`
	RecurringTemplateId *openapi_types.UUID `json:"recurring_template_id,omitempty"`

	// StartsAt When the task becomes active/visible.
	// For recurring items: set from the occurrence pattern.
	// For direct items: explicitly set to schedule future tasks.
	StartsAt *openapi_types.Date `json:"starts_at,omitempty"`
	Status   *ItemStatus         `json:"status,omitempty"`
	Tags     *[]string           `json:"tags,omitempty"`

	// Timezone IANA timezone
	Timezone  *string    `json:"timezone,omitempty"`
	Title     *string    `json:"title,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Title     *string             `json:"title,omitempty"`

	// TotalItems Total items in this list
	TotalItems *int `json:"total_items,omitempty"`

	// UndoneItems Items not yet done
	UndoneItems *int `json:"undone_items,omitempty"`
}

// UpdateItemRequest defines model for UpdateItemRequest.
type UpdateItemRequest struct {
	Item TodoItem `json:"item"`

	// UpdateMask Fields to update. Unknown fields are rejected with 400.
	UpdateMask []UpdateItemRequestUpdateMask `json:"update_mask"`
}

// UpdateItemRequestUpdateMask defines model for UpdateItemRequest.UpdateMask.
type UpdateItemRequestUpdateMask string

// UpdateItemResponse defines model for UpdateItemResponse.
type UpdateItemResponse struct {
	Item *TodoItem `json:"item,omitempty"`
}

// UpdateRecurringTemplateRequest defines model for UpdateRecurringTemplateRequest.
type UpdateRecurringTemplateRequest struct {
	Template RecurringItemTemplate `json:"template"`

	// UpdateMask Fields to update. Unknown fields are rejected with 400.
	UpdateMask []UpdateRecurringTemplateRequestUpdateMask `json:"update_mask"`
}

// UpdateRecurringTemplateRequestUpdateMask defines model for UpdateRecurringTemplateRequest.UpdateMask.
type UpdateRecurringTemplateRequestUpdateMask string

// UpdateRecurringTemplateResponse defines model for UpdateRecurringTemplateResponse.
type UpdateRecurringTemplateResponse struct {
	Template *RecurringItemTemplate `json:"template,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListDeadLetterJobsParams defines parameters for ListDeadLetterJobs.
type ListDeadLetterJobsParams struct {
	// Limit Maximum number of jobs to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DiscardDeadLetterJobJSONBody defines parameters for DiscardDeadLetterJob.
type DiscardDeadLetterJobJSONBody struct {
	// Note Reason for discarding
	Note *string `json:"note,omitempty"`
}

// ListListsParams defines parameters for ListLists.
type ListListsParams struct {
	// PageSize Number of lists per page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`

	// PageToken Page token from previous response
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// TitleContains Filter by title substring (case-insensitive)
	TitleContains *string `form:"title_contains,omitempty" json:"title_contains,omitempty"`

	// CreatedAfter Filter lists created after this time
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter lists created before this time
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`

	// SortBy Field to sort by
	SortBy *ListListsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir *ListListsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
}

// ListListsParamsSortBy defines parameters for ListLists.
type ListListsParamsSortBy string

// ListListsParamsSortDir defines parameters for ListLists.
type ListListsParamsSortDir string

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	// Status Filter by item status (can specify multiple).
	// If not specified, archived and cancelled items are excluded by default.
	// Use status=archived to explicitly include archived items.
	Status *[]ListItemsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Priority Filter by item priority (can specify multiple for OR logic)
	Priority *[]ListItemsParamsPriority `form:"priority,omitempty" json:"priority,omitempty"`

	// Tags Filter by tags (items must have all specified tags)
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// SortBy Field to sort by
	SortBy *ListItemsParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// SortDir Sort direction
	SortDir   *ListItemsParamsSortDir `form:"sort_dir,omitempty" json:"sort_dir,omitempty"`
	PageSize  *int                    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string                 `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListItemsParamsStatus defines parameters for ListItems.
type ListItemsParamsStatus string

// ListItemsParamsPriority defines parameters for ListItems.
type ListItemsParamsPriority string

// ListItemsParamsSortBy defines parameters for ListItems.
type ListItemsParamsSortBy string

// ListItemsParamsSortDir defines parameters for ListItems.
type ListItemsParamsSortDir string

// ListRecurringTemplatesParams defines parameters for ListRecurringTemplates.
type ListRecurringTemplatesParams struct {
	// ActiveOnly Filter for active templates only.
	// If not specified, defaults to true (only active templates returned).
	// Set to false to include inactive templates.
	ActiveOnly *bool `form:"active_only,omitempty" json:"active_only,omitempty"`
}

// DiscardDeadLetterJobJSONRequestBody defines body for DiscardDeadLetterJob for application/json ContentType.
type DiscardDeadLetterJobJSONRequestBody DiscardDeadLetterJobJSONBody

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = CreateListRequest

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = CreateItemRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = UpdateItemRequest

// CreateRecurringTemplateJSONRequestBody defines body for CreateRecurringTemplate for application/json ContentType.
type CreateRecurringTemplateJSONRequestBody = CreateRecurringTemplateRequest

// UpdateRecurringTemplateJSONRequestBody defines body for UpdateRecurringTemplate for application/json ContentType.
type UpdateRecurringTemplateJSONRequestBody = UpdateRecurringTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List pending dead letter jobs
	// (GET /v1/admin/dead-letter-jobs)
	ListDeadLetterJobs(w http.ResponseWriter, r *http.Request, params ListDeadLetterJobsParams)
	// Discard a dead letter job
	// (POST /v1/admin/dead-letter-jobs/{id}/discard)
	DiscardDeadLetterJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Retry a dead letter job
	// (POST /v1/admin/dead-letter-jobs/{id}/retry)
	RetryDeadLetterJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List all todo lists with pagination
	// (GET /v1/lists)
	ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams)
	// Create a new todo list
	// (POST /v1/lists)
	CreateList(w http.ResponseWriter, r *http.Request)
	// Get a todo list by ID
	// (GET /v1/lists/{id})
	GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List items in a list with filtering and sorting
	// (GET /v1/lists/{list_id}/items)
	ListItems(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListItemsParams)
	// Create a new item in a list
	// (POST /v1/lists/{list_id}/items)
	CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Delete a todo item
	// (DELETE /v1/lists/{list_id}/items/{item_id})
	DeleteItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID)
	// Update an existing item
	// (PATCH /v1/lists/{list_id}/items/{item_id})
	UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID)
	// List recurring templates for a list
	// (GET /v1/lists/{list_id}/recurring-templates)
	ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams)
	// Create a recurring item template
	// (POST /v1/lists/{list_id}/recurring-templates)
	CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID)
	// Delete a recurring template
	// (DELETE /v1/lists/{list_id}/recurring-templates/{template_id})
	DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
	// Get a recurring template by ID
	// (GET /v1/lists/{list_id}/recurring-templates/{template_id})
	GetRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
	// Update a recurring template
	// (PATCH /v1/lists/{list_id}/recurring-templates/{template_id})
	UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List pending dead letter jobs
// (GET /v1/admin/dead-letter-jobs)
func (_ Unimplemented) ListDeadLetterJobs(w http.ResponseWriter, r *http.Request, params ListDeadLetterJobsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Discard a dead letter job
// (POST /v1/admin/dead-letter-jobs/{id}/discard)
func (_ Unimplemented) DiscardDeadLetterJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retry a dead letter job
// (POST /v1/admin/dead-letter-jobs/{id}/retry)
func (_ Unimplemented) RetryDeadLetterJob(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all todo lists with pagination
// (GET /v1/lists)
func (_ Unimplemented) ListLists(w http.ResponseWriter, r *http.Request, params ListListsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new todo list
// (POST /v1/lists)
func (_ Unimplemented) CreateList(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a todo list by ID
// (GET /v1/lists/{id})
func (_ Unimplemented) GetList(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List items in a list with filtering and sorting
// (GET /v1/lists/{list_id}/items)
func (_ Unimplemented) ListItems(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new item in a list
// (POST /v1/lists/{list_id}/items)
func (_ Unimplemented) CreateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a todo item
// (DELETE /v1/lists/{list_id}/items/{item_id})
func (_ Unimplemented) DeleteItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing item
// (PATCH /v1/lists/{list_id}/items/{item_id})
func (_ Unimplemented) UpdateItem(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, itemId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List recurring templates for a list
// (GET /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) ListRecurringTemplates(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, params ListRecurringTemplatesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a recurring item template
// (POST /v1/lists/{list_id}/recurring-templates)
func (_ Unimplemented) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a recurring template
// (DELETE /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a recurring template by ID
// (GET /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) GetRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a recurring template
// (PATCH /v1/lists/{list_id}/recurring-templates/{template_id})
func (_ Unimplemented) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request, listId openapi_types.UUID, templateId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDeadLetterJobs operation middleware
func (siw *ServerInterfaceWrapper) ListDeadLetterJobs(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDeadLetterJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeadLetterJobs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscardDeadLetterJob operation middleware
func (siw *ServerInterfaceWrapper) DiscardDeadLetterJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscardDeadLetterJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RetryDeadLetterJob operation middleware
func (siw *ServerInterfaceWrapper) RetryDeadLetterJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RetryDeadLetterJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLists operation middleware
func (siw *ServerInterfaceWrapper) ListLists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListListsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "title_contains" -------------

	err = runtime.BindQueryParameter("form", true, false, "title_contains", r.URL.Query(), &params.TitleContains)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "title_contains", Err: err})
		return
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateList operation middleware
func (siw *ServerInterfaceWrapper) CreateList(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetList operation middleware
func (siw *ServerInterfaceWrapper) GetList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetList(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameter("form", true, false, "priority", r.URL.Query(), &params.Priority)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "priority", Err: err})
		return
	}

	// ------------- Optional query parameter "tags" -------------

	err = runtime.BindQueryParameter("form", true, false, "tags", r.URL.Query(), &params.Tags)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tags", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_by", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_dir" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort_dir", r.URL.Query(), &params.SortDir)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_dir", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListItems(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateItem(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteItem operation middleware
func (siw *ServerInterfaceWrapper) DeleteItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "item_id" -------------
	var itemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "item_id", chi.URLParam(r, "item_id"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "item_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateItem(w, r, listId, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringTemplates(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecurringTemplatesParams

	// ------------- Optional query parameter "active_only" -------------

	err = runtime.BindQueryParameter("form", true, false, "active_only", r.URL.Query(), &params.ActiveOnly)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "active_only", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringTemplates(w, r, listId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringTemplate(w, r, listId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringTemplate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "list_id" -------------
	var listId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "list_id", chi.URLParam(r, "list_id"), &listId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_id", Err: err})
		return
	}

	// ------------- Path parameter "template_id" -------------
	var templateId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "template_id", chi.URLParam(r, "template_id"), &templateId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "template_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringTemplate(w, r, listId, templateId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/admin/dead-letter-jobs", wrapper.ListDeadLetterJobs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/admin/dead-letter-jobs/{id}/discard", wrapper.DiscardDeadLetterJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/admin/dead-letter-jobs/{id}/retry", wrapper.RetryDeadLetterJob)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists", wrapper.ListLists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists", wrapper.CreateList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{id}", wrapper.GetList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/items", wrapper.ListItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/items", wrapper.CreateItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/lists/{list_id}/items/{item_id}", wrapper.DeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/lists/{list_id}/items/{item_id}", wrapper.UpdateItem)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.ListRecurringTemplates)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/lists/{list_id}/recurring-templates", wrapper.CreateRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.DeleteRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.GetRecurringTemplate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/lists/{list_id}/recurring-templates/{template_id}", wrapper.UpdateRecurringTemplate)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce2/bOBL/KgTvgE1xih9p090LsH9kt4/LYrfbS1ocFk1g0NLYZiORKkkl0Rb+7och",
	"JVmyKNt5OI/t/lHUtkjOcPibJ0f5SkOZpFKAMJoefKUKdCqFBvvlJxYdw5cMtMFvoRQGhP3I0jTmITNc",
	"iv5nLQX+psMZJAw//VPBhB7Qf/QXS/fdU91/rZRUxwUROp/PAxqBDhVPcTF6QI/EBYt5RFRBeB7QI2FA",
	"CRbbuffJiSNLNKgLUAQs+XlA30nzRmYiuj9WjkHLTIVAhDRkYmnPA/pRsMzMpOJ/wj3yUqdKdgkvzksq",
	"knCtuZiSw/dH5BxyinOLZZHqzwqYgSMDSQ1UqZIpKMMd4KIMRsz+PpEqwU80YgZ2DU+ABtTkKdADqo3i",
	"YooSwPFyMtFg5zT5fJUpu38yUTIh2jBl9IgZYiRxZMjO0cnv5IeXgyGJirHPeqfiaEI0GHLJzWwxKyjn",
	"/Fhb6V9kQb93KmhA4YolaYw8vv+w9x8fx6ANT5iBaFTSbHPeYqu18vPBb77FudCGiRBGKLTNpZgqLhU3",
	"+Tpo4NG9L8fOA6ogzBQuMjKQpDEzMOJRg2yW8chHsZJhe/P/m4EgZgbEMH1OxhDKBDRhoeEX0L/gmo9j",
	"6J2KN1KRij7hBhJ9YM/NnjbOlyE+BRECSZlBVS6mRVxBaMo5cIWawk2c2+lGEtxulMVAJpnJlGNEu/Nt",
	"yLNjYybTmwjyxI2cB9SwqZ1hGcIPrVWLH5hSzAoeD/JPKcADncN3h6R8THagN+0F5LvXGWpZ/8TI8Hwm",
	"4+S7Zw1EHSageMj67+By9IdU576NGW5iSy9hV7+CmJoZPdjb3w9owkX5fdiaZ0HyJeMKDdSnYpGzapgc",
	"f4bQmvi6bShMT8s4oHzWSfaDjCSuYkl3UPmVa9Npgap9LsRzMpNpiijDiTTYqgQcb10SiLljeZ0ELKMr",
	"JHBcKs6HQm9XGuQuA9syU8SNdCpY2iLSpSo3tYSthaYgwD0dWbckxShiuWMfJiyLDT14/nJ/2Y99kIbF",
	"ZDGZFJPJzuHJH+9+JjHLQT1z582TLKEH3z8f2NN23/BLwQsXBqagbm9L0VqNQikmfNoWxi8nv78j7iGZ",
	"SFVatV2dQsgnPET7ZbiYap+QausX89ZxeFzNeF9MQPuWi7BbysMXy0J+xXKNNrUQMxCeJBBxZiDOyU6H",
	"nP9dF/PQJ+WbmMw7s19eYZ5dR9m69Lt0o5sdDRdTRFG5rF/hXwGLfgXk8Rc5blO0Me0oAa3ZFLyCdCPc",
	"z57HE8ZjiK4VtJVYGKGduMG0TBgebz5vw5AkZtqMLqU6B1VEMa0hUvEpFywefZbjTSMdBUblo1BmLi73",
	"QPlaoZPviJsRu/+I2z+HMvKfaASG8bipXs2pEw6xX0Jc68y3qo/tZQ3tBmF7tm+9t2C27T3fgnlYbW54",
	"DTxbgSbyE43lJRpQiHiW0IDO+HRGA5qpKaaDZx5Y1iLQ2jJGRpJiGjFKlZwq0OhKxrEMzwGxGGHIGVCm",
	"whm/sL+E6OHjGCIvERRkw/7obmF9luMm5FZJrGnUWljySQ55wU3r1fHl5jwsIs02lAVcmVHKpjAy8hzE",
	"hgqBLOI/vRrC12PRgfkuWWxpgF6vApvz3KEMmxxxO2CpQTtiPM5pQC8Bzu2HMa8+JlKYmf2UA1P2w5eM",
	"KQOqmmJDHR/G/fy2ra0NBaI7K25sFBg/2gibC4Lzbxdpb+iAuR654kEN4mMpY2CicvtlaBFdN7ZAfdw0",
	"ErifzGDFKT7GFEAK4lSjn6Uo6YfJCVojHTPXUVe/QTIqb/iqbksp4HLzsNJHrPJHraVZaDIW39YG3NSC",
	"/aXKuYtt3IfZBcM8yv5aGG5yYpirAsjU8IRrw0O0AIW+5vjZKBmTneM3P5Pv957vPeuR/2bSQEQcAeL2",
	"QmJ+DuSUDk9pQE7pHv4HJuzdIpP6uwq95Sr0ApZ7g72Xu4Ph7nD/yRWnVxaZt2SQq4D4TuKzDVHWvSmD",
	"8dGokqwveLIPMV4yM65J7ArQbd+XCczNupayeY+9OszBkKgh/GoRn7w+WqmvvLG7XlG+PMhRwvR5m9E3",
	"HOLIBgtuWI98FOdCXgoycU+YAqIA2YPImfQXg0GvrhKLIl2B9pphOQsWMK5S3s7RlfuqG4qGjyq0w2vx",
	"g5bbrWmGL5FIuDhyzA09yU69ClkXoduRt/pYP7ztXak4KptfKNyyKLI1AHUCozjiGiy8p+0Jrn2h+xJ+",
	"FsmJL67uTrzuEkDViZxd53jvreiFfgvHcpOf4NyiMwWYAnWYmVkbBEX7AUmZ1hARpokbTWylA43pYdHA",
	"UGSlwCJQtOhVsPmhHb8wkjNjUtcKwcVEtikevz75MMli2/iAMZmRkbTGmjARWRtOEibYFBIQRSi6iBoW",
	"NZLKV9DfpJC4Gg3oBSjtqAx7g97A1qFTECzl9IA+7w16zxGdzMysXPoXwz6LEi76EbBoN7aJx25ZXJu6",
	"wBrPy279KKIHniqdXVCxBAwoTQ8+LW/3N5eUEZElY1BETggSQK1TYDKLfI7jvmSgUGEEs1KNecJNKWbW",
	"yBr3B7VUbzjw5Pvzs6DZm7Q3GNxZz8uKQqWnAQZH46ZRwsRJ2AoAj+bFYNhFrOK+3+jbmQd0321l9aRm",
	"E5RViyxJmMpLjlIQEeKpxVYZxH2ih4gMeoaTu4HS/8qjeT/iOmTKRjip1B7YvHIDmqXYNcDBwcSNJr/I",
	"MTl6VUIFAbxAig2kFhbLqAzqsFmXHZ+5yaDNTzLKr4WSpaRcGk8YewxMYx5qg3grBCS7QQA6d4a4AeIX",
	"nmqOHJcLY7aWhSFoPcniOL8xwl44OqsnVW1tdwHJAh6ELePxZnC012jdYGxXWh4TFLdktVaUlzxWCzdZ",
	"5pSRBa+T6dOBlN3vdQBV3ZZ0+j173bIOKu8qN2cXJCkokrIpdLg5e6mi+Z/gd3V7+8uublVZcx4sc/Oe",
	"TaGIZGyRIVVwwWWmSSnEVWy5u546Xy2j1Q6pYxT0OCc2OCE6GxcFpJ2QadjlQoPQHIPYZx2k7USMgA3j",
	"Qt+IvJN8kaUTNsHfbEpcJOc+slVOj6OpV2tX1g82YmUME6lgY17c8DthBuLI1omkMmScd9DFpyP71APF",
	"etUjqBKfxo/L/WrdDJ0gH66o5TKiTnYirjr4wRVrnDD7zf54dr+mtX0V2xEHamtFOVx4PfUGBq/WYv+w",
	"4SOL40Xeol2SkrIpF1X1ojCyzmaezYMOX7xoZKQ3j8NWHU67i3PezHDRSbcjreFWGFiTJpRm4sliw+2V",
	"MCLgcoEPDxzqPtfGbDXHuxw/Y5LoqpkkAcMiZliPfNRA3r7+QGqrFNer874rgxpJJmDCWVEVtRCdWKPM",
	"xbRHgyUgFg1B69y7PacnGP4t9zt1QbB6XeSJhHlvwRBWK6GMc3c6qwHXhMpa7FV1dWaJ9MhPOSn8UEDK",
	"BidbvalanIo5TAGBqzDOIojamKvajG6FurKt4DbQWxHI2YKUK3hjECeI6yDOSZLFhqcxFPemQpriEYfo",
	"GmJBGoUwe6cC9doR+7Fawcj6jRcXdt6CgF2yvOtKY9up6PbvDSrK0v1COO1q7t12tiXsqqi1vmxfgGmT",
	"2yIenhBdew5lYdl/EjZR+/2YxHLKw2ebyaNWql4hkWu3DC72/OIWe0YtJjsOM0mmDZmxC7DBR4U0O2bD",
	"vRbVec8+V/C/fwP+txVtV3dMtVNrDKzdfD7KMDz4ej9Z8C1y2m1nCs2+Ut+bpBbuD58p3L8zt25uydku",
	"BW7WnSAiiypq4eadrq5LM+zF5EO72rNt5jn12/cHyXMaN8gd4H7wPOf+kd1IjKwnrwDuQfGqYLX/Ff8b",
	"FSlTBDH4bh28rUZO7BojL7ADrTIVYYyLcsmOlhND3LLPiuYjIcVua7EUVMJQBHFeDHcruEBs6fbHPn8U",
	"2hf42l26Ezon6jvO6l74m24KMT7dSxzLfpmNcXfaHgPNTDhrW+hFA8q3ipG79wntjqyNfMJgKwys8QlF",
	"5PoN+QQnHMIEgSuuTWlbN/cHlU3ebbw5s7KU4ekkqRU2TkW9siFFnBddrLXRrikKV4OI7HDhHVAm9+hC",
	"TsAUq4xwxR8nLNaA6VGZybfX8DkR/9tEj7Zygql4SzS4f2+1pJC5rVoiB2THL/xS8KVcjSQbi9OXE9XO",
	"xZcUVa++bD0rWvGemMdifKgLpDNNejo5j08rLYCWI0SPAqxLelpT/toZUGdz6YOkQ929kCtQ/S3nR808",
	"o1KHdSqwuYfsf629+LGUQ/mylsenPi2PU+Gmi2r9VZetpzIVN3+VdKZtnNcbZG8Pke8PAvyNpm1dd97M",
	"9D7N+882RFsXoV2Rw6ps/G+03lOKfrugZbB9bjbQnG83gb+Bh6i/qGL1qP6KyqczRJv7O6JeLZMhi0kE",
	"FxDLNMFDD2im4uLVk4N+P8YBM6nNwQ+DH4Z9lnI6P5v/PwAA//9P5XwsvVUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
