// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/rezkam/mono/internal/application/auth"
	"github.com/rezkam/mono/internal/application/todo"
	"github.com/rezkam/mono/internal/config"
	"github.com/rezkam/mono/internal/http"
	"github.com/rezkam/mono/internal/http/handler"
	"github.com/rezkam/mono/internal/http/middleware"
	"github.com/rezkam/mono/internal/infrastructure/persistence/postgres"
	"time"
)

// Injectors from wire.go:

// InitializeHTTPServer wires everything together for the HTTP server.
func InitializeHTTPServer(ctx context.Context) (*HTTPServer, func(), error) {
	serverConfig, err := config.LoadServerConfig()
	if err != nil {
		return nil, nil, err
	}
	storageConfig := &serverConfig.StorageConfig
	store, err := provideStore(ctx, storageConfig)
	if err != nil {
		return nil, nil, err
	}
	todoConfig := provideTodoConfig()
	service := todo.NewService(store, todoConfig)
	server := handler.NewServer(service)
	duration := _wireDurationValue
	authenticator := auth.NewAuthenticator(ctx, store, duration)
	middlewareAuth := middleware.NewAuth(authenticator)
	mux := http.NewRouter(server, middlewareAuth)
	httpServer := NewHTTPServer(mux, serverConfig)
	return httpServer, func() {
	}, nil
}

var (
	_wireDurationValue = time.Duration(5 * time.Second)
)

// wire.go:

// ConfigSet provides configuration.
var ConfigSet = wire.NewSet(config.LoadServerConfig, wire.FieldsOf(new(*config.ServerConfig),
	"StorageConfig",
	"AuthConfig",
),
)

// DatabaseSet provides database connection and store.
// The Store implements both todo.Repository and auth.Repository
var DatabaseSet = wire.NewSet(
	provideStore, wire.Bind(new(todo.Repository), new(*postgres.Store)), wire.Bind(new(auth.Repository), new(*postgres.Store)),
)

// provideStore creates a postgres.Store from StorageConfig.
func provideStore(ctx context.Context, cfg *config.StorageConfig) (*postgres.Store, error) {
	return postgres.NewPostgresStore(ctx, cfg.StorageDSN)
}

// provideTodoConfig reads pagination config from environment.
func provideTodoConfig() todo.Config {
	defaultPageSize, _ := config.GetEnv[int]("MONO_DEFAULT_PAGE_SIZE")
	maxPageSize, _ := config.GetEnv[int]("MONO_MAX_PAGE_SIZE")

	return todo.Config{
		DefaultPageSize: defaultPageSize,
		MaxPageSize:     maxPageSize,
	}
}

// ServiceSet provides application services.
var ServiceSet = wire.NewSet(todo.NewService, provideTodoConfig)

// AuthSet provides authentication components.
var AuthSet = wire.NewSet(wire.Value(time.Duration(5*time.Second)), auth.NewAuthenticator)

// HTTPSet provides HTTP layer components.
var HTTPSet = wire.NewSet(handler.NewServer, middleware.NewAuth, http.NewRouter)
